//
// File:	pdat__SumOperation-dcomplex.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SumOperation.h"
#include "SumOperation.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::SumOperation< dcomplex >;
}
}
