//
// File:	pdat__CopyOperation-double.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CopyOperation.h"
#include "CopyOperation.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::CopyOperation< double >;
}
}
