//
// File:	pdat__SumOperation-int.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SumOperation.h"
#include "SumOperation.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::SumOperation< int >;
}
}
