//
// File:	pdat__CopyOperation-dcomplex.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CopyOperation.h"
#include "CopyOperation.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::CopyOperation< dcomplex >;
}
}
