//
// File:	AsyncBergerRigoutsos-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "AsyncBergerRigoutsos.h"
#include "AsyncBergerRigoutsos.C"

namespace SAMRAI {
   namespace mesh {
template class AsyncBergerRigoutsos< NDIM >;
}
}
