//
// File:	BalanceUtilities-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BalanceUtilities.h"
#include "BalanceUtilities.C"

namespace SAMRAI {
   namespace mesh {
template class BalanceUtilities< NDIM >;
}
}
