//
// File:	BoxGeneratorStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxGeneratorStrategy.h"
#include "BoxGeneratorStrategy.C"

namespace SAMRAI {
   namespace mesh {
template class BoxGeneratorStrategy< NDIM >;
}
}
