//
// File:	GriddingAlgorithm-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "GriddingAlgorithm.h"
#include "GriddingAlgorithm.C"

namespace SAMRAI {
   namespace mesh {
template class GriddingAlgorithm< NDIM >;
}
}
