//
// File:	HistogramBox-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HistogramBox.h"
#include "HistogramBox.C"

namespace SAMRAI {
   namespace mesh {
template class HistogramBox< NDIM >;
}
}
