//
// File:	LoadBalanceStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LoadBalanceStrategy.h"
#include "LoadBalanceStrategy.C"

namespace SAMRAI {
   namespace mesh {
template class LoadBalanceStrategy< NDIM >;
}
}
