##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	AsyncBergerRigoutsos-NDIM${NDIM}.o				\
	AsyncBergerRigoutsosNode-NDIM${NDIM}.o				\
	BalanceUtilities-NDIM${NDIM}.o					\
	BaseGriddingAlgorithm-NDIM${NDIM}.o				\
	BergerRigoutsos-NDIM${NDIM}.o BoxGeneratorStrategy-NDIM${NDIM}.o\
	GriddingAlgorithm-NDIM${NDIM}.o HistogramBox-NDIM${NDIM}.o	\
	LoadBalanceStrategy-NDIM${NDIM}.o LoadBalancer-NDIM${NDIM}.o	\
	MultiblockGriddingAlgorithm-NDIM${NDIM}.o			\
	MultiblockGriddingTagger-NDIM${NDIM}.o				\
	StandardTagAndInitStrategy-NDIM${NDIM}.o			\
	StandardTagAndInitialize-NDIM${NDIM}.o				\
	TagAndInitializeStrategy-NDIM${NDIM}.o				\
	tbox__Pointer-mesh__AsyncBergerRigoutsos-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__BaseGriddingAlgorithm-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__BergerRigoutsos-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__BoxGeneratorStrategy-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__GriddingAlgorithm-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__LoadBalanceStrategy-NDIM${NDIM}.o		\
	tbox__Pointer-mesh__LoadBalancer-NDIM${NDIM}.o			\
	tbox__Pointer-mesh__MultiblockGriddingAlgorithm-NDIM${NDIM}.o	\
	tbox__Pointer-mesh__StandardTagAndInitStrategy-NDIM${NDIM}.o	\
	tbox__Pointer-mesh__StandardTagAndInitialize-NDIM${NDIM}.o	\
	tbox__Pointer-mesh__TagAndInitializeStrategy-NDIM${NDIM}.o


libchar:	


libbool:	


libfloat:	


libdcomplex:	
