//
// File:	MultiblockGriddingAlgorithm-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockGriddingAlgorithm.h"
#include "MultiblockGriddingAlgorithm.C"

namespace SAMRAI {
   namespace mesh {
template class MultiblockGriddingAlgorithm< NDIM >;
}
}
