//
// File:	MultiblockGriddingTagger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockGriddingTagger.h"
#include "MultiblockGriddingTagger.C"

namespace SAMRAI {
   namespace mesh {
template class MultiblockGriddingTagger< NDIM >;
}
}
