//
// File:	StandardTagAndInitStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "StandardTagAndInitStrategy.h"
#include "StandardTagAndInitStrategy.C"

namespace SAMRAI {
   namespace mesh {
template class StandardTagAndInitStrategy< NDIM >;
}
}
