//
// File:	TagAndInitializeStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "TagAndInitializeStrategy.h"
#include "TagAndInitializeStrategy.C"

namespace SAMRAI {
   namespace mesh {
template class TagAndInitializeStrategy< NDIM >;
}
}
