//
// File:	tbox__List-tbox__Statistic__PatchStatRecord.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "tbox/Statistic.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< tbox::Statistic::PatchStatRecord > *tbox::ListNode< tbox::Statistic::PatchStatRecord >::s_free_list=0;
bool tbox::ListNode< tbox::Statistic::PatchStatRecord >::s_registered_callback=false;
#endif
template class tbox::List< tbox::Statistic::PatchStatRecord >;
template class tbox::ListIterator< tbox::Statistic::PatchStatRecord >;
template class tbox::ListNode< tbox::Statistic::PatchStatRecord >;
}
}
