//
// File:	tbox__Array-tbox__Pointer-tbox__SiloDatabase.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/Pointer.h"
#include "tbox/SiloDatabase.h"

namespace SAMRAI {
   namespace tbox {
#ifdef HAVE_SILO
template class tbox::Array< tbox::Pointer< tbox::SiloDatabase > >;
#endif
}
}
