//
// File:	tbox__Array-tbox__SAMRAI_MPI__status.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/SAMRAI_MPI.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::SAMRAI_MPI::status >;
}
}
