//
// File:	tbox__Array-tbox__List-tbox__Pointer-tbox__Transaction.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/List.h"
#include "tbox/Pointer.h"
#include "tbox/Transaction.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::List< tbox::Pointer< tbox::Transaction > > >;
}
}
