//
// File:	tbox__MathUtilities-char.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/MathUtilities.h"
#include "tbox/MathUtilities.C"

namespace SAMRAI {
   namespace tbox {
template class tbox::MathUtilities< char >;
}
}
