//
// File:	tbox__List-string.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include <string>
using namespace std;

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< string > *tbox::ListNode< string >::s_free_list=0;
bool tbox::ListNode< string >::s_registered_callback=false;
#endif
template class tbox::List< string >;
template class tbox::ListIterator< string >;
template class tbox::ListNode< string >;
}
}
