//
// File:	tbox__Array-string.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include <string>
using namespace std;

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< string >;
}
}
