//
// File:	tbox__Pointer-tbox__HDFDatabase.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "tbox/HDFDatabase.h"

namespace SAMRAI {
   namespace tbox {
#ifdef HAVE_HDF5
template class tbox::Pointer< tbox::HDFDatabase >;
#endif
}
}
