//
// File:	tbox__List-tbox__Parser__ParseData.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "tbox/Parser.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< tbox::Parser::ParseData > *tbox::ListNode< tbox::Parser::ParseData >::s_free_list=0;
bool tbox::ListNode< tbox::Parser::ParseData >::s_registered_callback=false;
#endif
template class tbox::List< tbox::Parser::ParseData >;
template class tbox::ListIterator< tbox::Parser::ParseData >;
template class tbox::ListNode< tbox::Parser::ParseData >;
}
}
