//
// File:	tbox__List-tbox__InputDatabase__KeyData.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "tbox/InputDatabase.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< tbox::InputDatabase::KeyData > *tbox::ListNode< tbox::InputDatabase::KeyData >::s_free_list=0;
bool tbox::ListNode< tbox::InputDatabase::KeyData >::s_registered_callback=false;
#endif
template class tbox::List< tbox::InputDatabase::KeyData >;
template class tbox::ListIterator< tbox::InputDatabase::KeyData >;
template class tbox::ListNode< tbox::InputDatabase::KeyData >;
}
}
