//
// File:	tbox__Array-tbox__DatabaseBox.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/DatabaseBox.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::DatabaseBox >;
}
}
