//
// File:	HyperbolicLevelIntegrator-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HyperbolicLevelIntegrator.h"
#include "HyperbolicLevelIntegrator.C"

namespace SAMRAI {
   namespace algs {
template class HyperbolicLevelIntegrator< NDIM >;
}
}
