//
// File:	ImplicitIntegrator-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ImplicitIntegrator.h"
#include "ImplicitIntegrator.C"

namespace SAMRAI {
   namespace algs {
template class ImplicitIntegrator< NDIM >;
}
}
