//
// File:	LocallyActiveDataPatchBoundaryNodeSum-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataPatchBoundaryNodeSum.h"
#include "LocallyActiveDataPatchBoundaryNodeSum.C"

namespace SAMRAI {
   namespace algs {
template class LocallyActiveDataPatchBoundaryNodeSum< NDIM >;
}
}
