//
// File:	LocallyActiveDataPatchBoundaryEdgeSum-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataPatchBoundaryEdgeSum.h"
#include "LocallyActiveDataPatchBoundaryEdgeSum.C"

namespace SAMRAI {
   namespace algs {
template class LocallyActiveDataPatchBoundaryEdgeSum< NDIM >;
}
}
