//
// File:	MethodOfLinesIntegrator-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MethodOfLinesIntegrator.h"
#include "MethodOfLinesIntegrator.C"

namespace SAMRAI {
   namespace algs {
template class MethodOfLinesIntegrator< NDIM >;
}
}
