//
// File:	OuteredgeSumTransaction-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuteredgeSumTransaction.h"
#include "OuteredgeSumTransaction.C"

namespace SAMRAI {
   namespace algs {
template class OuteredgeSumTransaction< NDIM >;
}
}
