//
// File:	OuteredgeSumTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuteredgeSumTransactionFactory.h"
#include "OuteredgeSumTransactionFactory.C"

namespace SAMRAI {
   namespace algs {
template class OuteredgeSumTransactionFactory< NDIM >;
}
}
