//
// File:	OuternodeSumTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuternodeSumTransactionFactory.h"
#include "OuternodeSumTransactionFactory.C"

namespace SAMRAI {
   namespace algs {
template class OuternodeSumTransactionFactory< NDIM >;
}
}
