//
// File:	tbox__Array-tbox__Pointer-algs__PatchBoundaryNodeSum-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/Pointer.h"
#include "PatchBoundaryNodeSum.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::Pointer< algs::PatchBoundaryNodeSum< NDIM > > >;
}
}
