//
// File:	TimeRefinementLevelStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "TimeRefinementLevelStrategy.h"
#include "TimeRefinementLevelStrategy.C"

namespace SAMRAI {
   namespace algs {
template class TimeRefinementLevelStrategy< NDIM >;
}
}
