//
// File:	TimeRefinementIntegrator-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "TimeRefinementIntegrator.h"
#include "TimeRefinementIntegrator.C"

namespace SAMRAI {
   namespace algs {
template class TimeRefinementIntegrator< NDIM >;
}
}
