//
// File:	CartesianRobinBcHelper-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianRobinBcHelper.h"
#include "CartesianRobinBcHelper.C"

namespace SAMRAI {
   namespace solv {
template class CartesianRobinBcHelper< NDIM >;
}
}
