//
// File:	CellPoissonFACOps-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellPoissonFACOps.h"
#include "CellPoissonFACOps.C"

namespace SAMRAI {
   namespace solv {
template class CellPoissonFACOps< NDIM >;
}
}
