//
// File:	CellPoissonHypreSolver-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellPoissonHypreSolver.h"
#include "CellPoissonHypreSolver.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_HYPRE
template class CellPoissonHypreSolver< NDIM >;
#endif
}
}
