//
// File:	CellPoissonFACSolver-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellPoissonFACSolver.h"
#include "CellPoissonFACSolver.C"

namespace SAMRAI {
   namespace solv {
template class CellPoissonFACSolver< NDIM >;
}
}
