//
// File:	FACOperatorStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FACOperatorStrategy.h"
#include "FACOperatorStrategy.C"

namespace SAMRAI {
   namespace solv {
template class FACOperatorStrategy< NDIM >;
}
}
