//
// File:	KINSOL_SAMRAIContext-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "KINSOL_SAMRAIContext.h"
#include "KINSOL_SAMRAIContext.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_SUNDIALS
template class KINSOL_SAMRAIContext< NDIM >;
#endif
}
}
