//
// File:	LocationIndexRobinBcCoefs-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocationIndexRobinBcCoefs.h"
#include "LocationIndexRobinBcCoefs.C"

namespace SAMRAI {
   namespace solv {
template class LocationIndexRobinBcCoefs< NDIM >;
}
}
