//
// File:	PETSc_SAMRAIVectorReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PETSc_SAMRAIVectorReal.h"
#include "PETSc_SAMRAIVectorReal.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_PETSC
template class PETSc_SAMRAIVectorReal< NDIM,double >;
#endif
}
}
