//
// File:	SAMRAIVectorReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SAMRAIVectorReal.h"
#include "SAMRAIVectorReal.C"

namespace SAMRAI {
   namespace solv {
template class SAMRAIVectorReal< NDIM,double >;
}
}
