//
// File:	SNES_SAMRAIContext-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SNES_SAMRAIContext.h"
#include "SNES_SAMRAIContext.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_PETSC
template class SNES_SAMRAIContext< NDIM >;
#endif
}
}
