//
// File:	Sundials_SAMRAIVector-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "Sundials_SAMRAIVector.h"
#include "Sundials_SAMRAIVector.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_SUNDIALS
template class Sundials_SAMRAIVector< NDIM >;
#endif
}
}
