//
// File:	tbox__Pointer-solv__SAMRAIVectorReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "SAMRAIVectorReal.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< solv::SAMRAIVectorReal< NDIM,double > >;
}
}
