//
// File:	CartesianVizamraiDataWriter-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianVizamraiDataWriter.h"
#include "CartesianVizamraiDataWriter.C"

namespace SAMRAI {
   namespace appu {
template class CartesianVizamraiDataWriter< NDIM >;
}
}
