//
// File:	CubesPatchInterface-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CubesPatchInterface.h"
#include "CubesPatchInterface.C"

namespace SAMRAI {
   namespace appu {
template class CubesPatchInterface< NDIM >;
}
}
