//
// File:	CutCell-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CutCell.h"
#include "CutCell.C"

namespace SAMRAI {
   namespace appu {
template class CutCell< NDIM >;
}
}
