//
// File:	ElevenPatchInterface-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ElevenPatchInterface.h"
#include "ElevenPatchInterface.C"

namespace SAMRAI {
   namespace appu {
template class ElevenPatchInterface< NDIM >;
}
}
