//
// File:	EmbeddedBoundaryShapePolygon-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "EmbeddedBoundaryShapePolygon.h"
#include "EmbeddedBoundaryShapePolygon.C"

namespace SAMRAI {
   namespace appu {
template class EmbeddedBoundaryShapePolygon< NDIM >;
}
}
