##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	BoundaryNode-NDIM${NDIM}.o					\
	CartesianVizamraiDataWriter-NDIM${NDIM}.o			\
	CubesPatchInterface-NDIM${NDIM}.o CutCell-NDIM${NDIM}.o		\
	ElevenPatchInterface-NDIM${NDIM}.o				\
	EmbeddedBoundaryGeometry-NDIM${NDIM}.o				\
	EmbeddedBoundaryShape-NDIM${NDIM}.o				\
	EmbeddedBoundaryShapePolygon-NDIM${NDIM}.o			\
	EmbeddedBoundaryShapeSphere-NDIM${NDIM}.o			\
	VisDerivedDataStrategy-NDIM${NDIM}.o				\
	VisItDataWriter-NDIM${NDIM}.o					\
	VisMaterialsDataStrategy-NDIM${NDIM}.o				\
	pdat__IndexData-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	pdat__IndexDataFactory-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	pdat__IndexVariable-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	tbox__Array-appu__CutCell_NDIM_${NDIM}.o			\
	tbox__List-appu__VisItDataWriter_NDIM___VisItItem${NDIM}.o	\
	tbox__Pointer-appu__CutCell_NDIM_${NDIM}.o			\
	tbox__Array-appu__BoundaryNode-NDIM${NDIM}.o			\
	tbox__Array-tbox__Pointer-appu__CutCell_NDIM_${NDIM}.o		\
	tbox__List-appu__CartesianVizamraiDataWriter_NDIM___VizamraiItem-NDIM${NDIM}.o\
	tbox__Pointer-appu__CartesianVizamraiDataWriter-NDIM${NDIM}.o	\
	tbox__Pointer-appu__CubesPatchInterface-NDIM${NDIM}.o		\
	tbox__Pointer-appu__ElevenPatchInterface-NDIM${NDIM}.o		\
	tbox__Pointer-appu__EmbeddedBoundaryGeometry-NDIM${NDIM}.o	\
	tbox__Pointer-appu__EmbeddedBoundaryShape-NDIM${NDIM}.o		\
	tbox__Pointer-appu__VisItDataWriter-NDIM${NDIM}.o		\
	tbox__Pointer-pdat__IndexData-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	tbox__Pointer-pdat__IndexDataFactory-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	tbox__Pointer-pdat__IndexVariable-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_${NDIM}.o\
	tbox__Array-tbox__Pointer-appu__EmbeddedBoundaryShape-NDIM${NDIM}.o


libchar:	


libbool:	


libfloat:	


libdcomplex:	
