//
// File:	pdat__IndexVariable-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_X.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "IndexVariable.h"
#include "IndexVariable.C"
#include "CutCell.h"
#include "CellGeometry.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::IndexVariable< NDIM,appu::CutCell<NDIM>,pdat::CellGeometry<NDIM> >;
}
}
