//
// File:	tbox__List-appu__VisItDataWriter_NDIM___VisItItemX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "VisItDataWriter.h"

namespace SAMRAI {
   namespace tbox {
#ifdef HAVE_HDF5
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< appu::VisItDataWriter<NDIM>::VisItItem > *tbox::ListNode< appu::VisItDataWriter<NDIM>::VisItItem >::s_free_list=0;
bool tbox::ListNode< appu::VisItDataWriter<NDIM>::VisItItem >::s_registered_callback=false;
#endif
template class tbox::List< appu::VisItDataWriter<NDIM>::VisItItem >;
template class tbox::ListIterator< appu::VisItDataWriter<NDIM>::VisItItem >;
template class tbox::ListNode< appu::VisItDataWriter<NDIM>::VisItItem >;
#endif
}
}
