//
// File:	tbox__Pointer-appu__CutCell_NDIM_X.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "CutCell.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< appu::CutCell<NDIM> >;
}
}
