//
// File:	tbox__Pointer-pdat__IndexDataFactory-NDIM_appu__CutCell_NDIM__pdat__CellGeometry_NDIM_X.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "IndexDataFactory.h"
#include "CutCell.h"
#include "CellGeometry.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< pdat::IndexDataFactory< NDIM,appu::CutCell<NDIM>,pdat::CellGeometry<NDIM> > >;
}
}
