//
// File:	VisItDataWriter-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "VisItDataWriter.h"
#include "VisItDataWriter.C"

namespace SAMRAI {
   namespace appu {
#ifdef HAVE_HDF5
template class VisItDataWriter< NDIM >;
#endif
}
}
