//
// File:	VisMaterialsDataStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "VisMaterialsDataStrategy.h"
#include "VisMaterialsDataStrategy.C"

namespace SAMRAI {
   namespace appu {
template class VisMaterialsDataStrategy< NDIM >;
}
}
