//
// File:	BlockPatchGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BlockPatchGeometry.h"
#include "BlockPatchGeometry.C"

namespace SAMRAI {
   namespace geom {
template class BlockPatchGeometry< NDIM >;
}
}
