//
// File:	CartesianCellFloatWeightedAverage-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianCellFloatWeightedAverage.h"
#include "CartesianCellFloatWeightedAverage.C"

namespace SAMRAI {
   namespace geom {
template class CartesianCellFloatWeightedAverage< NDIM >;
}
}
