//
// File:	CartesianOutersideDoubleWeightedAverage-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianOutersideDoubleWeightedAverage.h"
#include "CartesianOutersideDoubleWeightedAverage.C"

namespace SAMRAI {
   namespace geom {
template class CartesianOutersideDoubleWeightedAverage< NDIM >;
}
}
