//
// File:	CartesianCellFloatLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianCellFloatLinearRefine.h"
#include "CartesianCellFloatLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianCellFloatLinearRefine< NDIM >;
}
}
