//
// File:	CartesianFaceFloatConservativeLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianFaceFloatConservativeLinearRefine.h"
#include "CartesianFaceFloatConservativeLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianFaceFloatConservativeLinearRefine< NDIM >;
}
}
