//
// File:	CartesianCellDoubleConservativeLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianCellDoubleConservativeLinearRefine.h"
#include "CartesianCellDoubleConservativeLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianCellDoubleConservativeLinearRefine< NDIM >;
}
}
