//
// File:	CartesianPatchGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianPatchGeometry.h"
#include "CartesianPatchGeometry.C"

namespace SAMRAI {
   namespace geom {
template class CartesianPatchGeometry< NDIM >;
}
}
