//
// File:	CartesianNodeDoubleLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianNodeDoubleLinearRefine.h"
#include "CartesianNodeDoubleLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianNodeDoubleLinearRefine< NDIM >;
}
}
