//
// File:	CartesianSideFloatConservativeLinearRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianSideFloatConservativeLinearRefine.h"
#include "CartesianSideFloatConservativeLinearRefine.C"

namespace SAMRAI {
   namespace geom {
template class CartesianSideFloatConservativeLinearRefine< NDIM >;
}
}
