//
// File:	CartesianGridGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CartesianGridGeometry.h"
#include "CartesianGridGeometry.C"

namespace SAMRAI {
   namespace geom {
template class CartesianGridGeometry< NDIM >;
}
}
