##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	BlockGridGeometry-NDIM${NDIM}.o BlockPatchGeometry-NDIM${NDIM}.o\
	CartesianCellDoubleConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianCellDoubleLinearRefine-NDIM${NDIM}.o			\
	CartesianCellDoubleWeightedAverage-NDIM${NDIM}.o		\
	CartesianEdgeDoubleConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianEdgeDoubleWeightedAverage-NDIM${NDIM}.o		\
	CartesianFaceDoubleConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianFaceDoubleWeightedAverage-NDIM${NDIM}.o		\
	CartesianGridGeometry-NDIM${NDIM}.o				\
	CartesianNodeDoubleLinearRefine-NDIM${NDIM}.o			\
	CartesianOuterfaceDoubleWeightedAverage-NDIM${NDIM}.o		\
	CartesianOutersideDoubleWeightedAverage-NDIM${NDIM}.o		\
	CartesianPatchGeometry-NDIM${NDIM}.o				\
	CartesianSideDoubleConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianSideDoubleWeightedAverage-NDIM${NDIM}.o		\
	SkeletonCoarsen-NDIM${NDIM}.o SkeletonCoarsen-NDIM${NDIM}.o	\
	SkeletonGridGeometry-NDIM${NDIM}.o				\
	SkeletonPatchGeometry-NDIM${NDIM}.o SkeletonRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__BlockGridGeometry-NDIM${NDIM}.o		\
	tbox__Pointer-geom__BlockPatchGeometry-NDIM${NDIM}.o		\
	tbox__Pointer-geom__CartesianCellDoubleConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellDoubleLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellDoubleWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianEdgeDoubleConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianEdgeDoubleWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianFaceDoubleWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianGridGeometry-NDIM${NDIM}.o		\
	tbox__Pointer-geom__CartesianNodeDoubleLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianOuterfaceDoubleWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianPatchGeometry-NDIM${NDIM}.o	\
	tbox__Pointer-geom__CartesianSideDoubleConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianSideDoubleWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__SkeletonGridGeometry-NDIM${NDIM}.o		\
	tbox__Pointer-geom__SkeletonPatchGeometry-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-geom__SkeletonGridGeometry-NDIM${NDIM}.o


libchar:	


libbool:	


libfloat:	CartesianCellFloatConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianCellFloatLinearRefine-NDIM${NDIM}.o			\
	CartesianCellFloatWeightedAverage-NDIM${NDIM}.o			\
	CartesianEdgeFloatConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianEdgeFloatWeightedAverage-NDIM${NDIM}.o			\
	CartesianFaceFloatConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianFaceFloatWeightedAverage-NDIM${NDIM}.o			\
	CartesianNodeFloatLinearRefine-NDIM${NDIM}.o			\
	CartesianOuterfaceFloatWeightedAverage-NDIM${NDIM}.o		\
	CartesianSideFloatConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianSideFloatWeightedAverage-NDIM${NDIM}.o			\
	tbox__Pointer-geom__CartesianCellFloatConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellFloatLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellFloatWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianEdgeFloatConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianEdgeFloatWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianFaceFloatWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianNodeFloatLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianOuterfaceFloatWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianSideFloatConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianSideFloatWeightedAverage-NDIM${NDIM}.o


libdcomplex:	CartesianCellComplexConservativeLinearRefine-NDIM${NDIM}.o	\
	CartesianCellComplexLinearRefine-NDIM${NDIM}.o			\
	CartesianCellComplexWeightedAverage-NDIM${NDIM}.o		\
	CartesianEdgeComplexWeightedAverage-NDIM${NDIM}.o		\
	CartesianFaceComplexWeightedAverage-NDIM${NDIM}.o		\
	CartesianFaceFloatWeightedAverage-NDIM${NDIM}.o			\
	CartesianNodeComplexLinearRefine-NDIM${NDIM}.o			\
	CartesianOuterfaceComplexWeightedAverage-NDIM${NDIM}.o		\
	CartesianSideComplexWeightedAverage-NDIM${NDIM}.o		\
	tbox__Pointer-geom__CartesianCellComplexConservativeLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellComplexLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianCellComplexWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianEdgeComplexWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianFaceComplexWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianNodeComplexLinearRefine-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianOuterfaceComplexWeightedAverage-NDIM${NDIM}.o\
	tbox__Pointer-geom__CartesianSideComplexWeightedAverage-NDIM${NDIM}.o
