//
// File:	SkeletonGridGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SkeletonGridGeometry.h"
#include "SkeletonGridGeometry.C"

namespace SAMRAI {
   namespace geom {
template class SkeletonGridGeometry< NDIM >;
}
}
