//
// File:	SkeletonCoarsen-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SkeletonCoarsen.h"
#include "SkeletonCoarsen.C"

namespace SAMRAI {
   namespace geom {
template class SkeletonCoarsen< NDIM >;
}
}
