#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/tools/vizamrai/cvis/cvish $
## Package:     Vizamrai
## Copyright:   (c) 1997-2000 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1704 $
## Modified:    $LastChangedDate: 2007-11-13 16:32:40 -0800 (Tue, 13 Nov 2007) $
## Description: Script used to invoke the CASC Visualization toolkit
##

LD_LIBRARY_PATH="$LD_LIBRARY_PATH:CVIS_INSTALL/lib"
export LD_LIBRARY_PATH

TCLLIBPATH="CVIS_INSTALL/lib/cvis/ $TCLLIBPATH"
export TCLLIBPATH
CVIS_INSTALL/bin/vtk $*
