#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/source/scripts/source_manipulation/findHeaderFiles $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: Find all header files
##

BIN=`dirname $0`
cd `dirname $0`/../../../source || exit 1;
echo `pwd`
test -d "hierarchy/patches" || exit 1

perl scripts/source_manipulation/findHeaderFiles.pl > scripts/source_manipulation/headers.data

exit
