//
// File:	BasePatchLevel-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BasePatchLevel.h"
#include "BasePatchLevel.C"

namespace SAMRAI {
   namespace hier {
template class BasePatchLevel< NDIM >;
}
}
