//
// File:	BinaryTree-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BinaryTree.h"
#include "BinaryTree.C"

namespace SAMRAI {
   namespace hier {
template class BinaryTree< NDIM >;
}
}
