//
// File:	BoundaryBox-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoundaryBox.h"
#include "BoundaryBox.C"

namespace SAMRAI {
   namespace hier {
template class BoundaryBox< NDIM >;
}
}
