//
// File:	BoundaryBoxUtils-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoundaryBoxUtils.h"
#include "BoundaryBoxUtils.C"

namespace SAMRAI {
   namespace hier {
template class BoundaryBoxUtils< NDIM >;
}
}
