//
// File:	Box-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "Box.h"
#include "Box.C"

namespace SAMRAI {
   namespace hier {
template class Box< NDIM >;
template class BoxIterator< NDIM >;
template std::istream& operator >> (std::istream& s, Box<NDIM>& box);
template std::ostream& operator << (std::ostream& s, const Box<NDIM>& box);
}
}
