//
// File:	BoxArray-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxArray.h"
#include "BoxArray.C"

namespace SAMRAI {
   namespace hier {
template class BoxArray< NDIM >;
}
}
