//
// File:	BoxGraphUtilities-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxGraphUtilities.h"
#include "BoxGraphUtilities.C"

namespace SAMRAI {
   namespace hier {
template class BoxGraphUtilities< NDIM >;
}
}
