//
// File:	BoxOverlap-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxOverlap.h"
#include "BoxOverlap.C"

namespace SAMRAI {
   namespace hier {
template class BoxOverlap< NDIM >;
}
}
