//
// File:	BoxTree-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxTree.h"
#include "BoxTree.C"

namespace SAMRAI {
   namespace hier {
template class BoxTree< NDIM >;
}
}
