//
// File:	BoxTreeNode-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxTreeNode.h"
#include "BoxTreeNode.C"

namespace SAMRAI {
   namespace hier {
template class BoxTreeNode< NDIM >;
}
}
