//
// File:	BoxUtilities-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "BoxUtilities.h"
#include "BoxUtilities.C"

namespace SAMRAI {
   namespace hier {
template class BoxUtilities< NDIM >;
}
}
