//
// File:	IntVector-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "IntVector.h"
#include "IntVector.C"

namespace SAMRAI {
   namespace hier {
template class IntVector< NDIM >;
template std::istream& operator >> (std::istream& s, IntVector<NDIM>& box);
template std::ostream& operator << (std::ostream& s, const IntVector<NDIM>& box);
}
}
