//
// File:	LayerEdgeSet-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LayerEdgeSet.h"
#include "LayerEdgeSet.C"

namespace SAMRAI {
   namespace hier {
template class LayerEdgeSet< NDIM >;
}
}
