//
// File:	LayerNodeSet-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LayerNodeSet.h"
#include "LayerNodeSet.C"

namespace SAMRAI {
   namespace hier {
template class LayerNodeSet< NDIM >;
}
}
