//
// File:	LocallyActiveDataPatchLevelManager-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataPatchLevelManager.h"
#include "LocallyActiveDataPatchLevelManager.C"

namespace SAMRAI {
   namespace hier {
template class LocallyActiveDataPatchLevelManager< NDIM >;
template class LocallyActiveDataPatchLevelIterator< NDIM >;
}
}
