##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	BasePatchHierarchy-NDIM${NDIM}.o BasePatchLevel-NDIM${NDIM}.o	\
	BinaryTree-NDIM${NDIM}.o BoundaryBox-NDIM${NDIM}.o		\
	BoundaryBoxUtils-NDIM${NDIM}.o BoundaryLookupTable-NDIM${NDIM}.o\
	Box-NDIM${NDIM}.o BoxArray-NDIM${NDIM}.o BoxComm-NDIM${NDIM}.o	\
	BoxGeometry-NDIM${NDIM}.o BoxGraph-NDIM${NDIM}.o		\
	BoxGraphUtilities-NDIM${NDIM}.o BoxIOUtility-NDIM${NDIM}.o	\
	BoxList-NDIM${NDIM}.o BoxOverlap-NDIM${NDIM}.o			\
	BoxTop-NDIM${NDIM}.o BoxTree-NDIM${NDIM}.o			\
	BoxTreeNode-NDIM${NDIM}.o BoxUtilities-NDIM${NDIM}.o		\
	CoarseFineBoundary-NDIM${NDIM}.o GridGeometry-NDIM${NDIM}.o	\
	Index-NDIM${NDIM}.o IntVector-NDIM${NDIM}.o			\
	LayerEdgeSet-NDIM${NDIM}.o LayerHierarchy-NDIM${NDIM}.o		\
	LayerNode-NDIM${NDIM}.o LayerNodeSet-NDIM${NDIM}.o		\
	LocallyActiveDataPatchLevelManager-NDIM${NDIM}.o		\
	LocallyActiveVariableDatabase-NDIM${NDIM}.o			\
	MBUtilities-NDIM${NDIM}.o MultiblockDataTranslator-NDIM${NDIM}.o\
	MultiblockGridGeometry-NDIM${NDIM}.o				\
	MultiblockPatchHierarchy-NDIM${NDIM}.o				\
	MultiblockPatchLevel-NDIM${NDIM}.o Patch-NDIM${NDIM}.o		\
	PatchConfigurationUtilities-NDIM${NDIM}.o			\
	PatchData-NDIM${NDIM}.o PatchDataFactory-NDIM${NDIM}.o		\
	PatchDescriptor-NDIM${NDIM}.o PatchFactory-NDIM${NDIM}.o	\
	PatchGeometry-NDIM${NDIM}.o PatchHierarchy-NDIM${NDIM}.o	\
	PatchLevel-NDIM${NDIM}.o PatchLevelFactory-NDIM${NDIM}.o	\
	Variable-NDIM${NDIM}.o VariableDatabase-NDIM${NDIM}.o		\
	tbox__Array-hier__BinaryTree_NDIM___binTreeNode${NDIM}.o	\
	tbox__Array-hier__BoxGraph_NDIM___GraphNode${NDIM}.o		\
	tbox__Array-hier__BoxTreeNode_NDIM___Triple${NDIM}.o		\
	tbox__Array-hier__ComponentSelector.o				\
	tbox__Array-hier__PatchConfigurationUtilities_NDIM___NeighborPatchInfo${NDIM}.o\
	tbox__Array-hier__PatchConfigurationUtilities_NDIM___PatchInfoPointer${NDIM}.o\
	tbox__Array-hier__PatchConfigurationUtilities_NDIM___PatchLevelInfo${NDIM}.o\
	tbox__List-hier__BoxTreeNode_NDIM___Triple${NDIM}.o		\
	tbox__List-hier__MultiblockPatchHierarchy_NDIM___Neighbor${NDIM}.o\
	tbox__Pointer-hier__ComponentSelector.o				\
	tbox__Pointer-hier__VariableContext.o				\
	tbox__Array-hier__BoundaryBox-NDIM${NDIM}.o			\
	tbox__Array-hier__Box-NDIM${NDIM}.o				\
	tbox__Array-hier__BoxArray-NDIM${NDIM}.o			\
	tbox__Array-hier__BoxList-NDIM${NDIM}.o				\
	tbox__Array-hier__CoarseFineBoundary-NDIM${NDIM}.o		\
	tbox__Array-hier__Index-NDIM${NDIM}.o				\
	tbox__Array-hier__IntVector-NDIM${NDIM}.o			\
	tbox__Array-hier__LayerEdgeSet-NDIM${NDIM}.o			\
	tbox__Array-hier__LayerNodeSet-NDIM${NDIM}.o			\
	tbox__Array-tbox__List-hier__MultiblockPatchHierarchy_NDIM___Neighbor${NDIM}.o\
	tbox__Array-tbox__Pointer-hier__ComponentSelector.o		\
	tbox__Array-tbox__Pointer-hier__VariableContext.o		\
	tbox__List-hier__BoundaryBox-NDIM${NDIM}.o			\
	tbox__List-hier__Box-NDIM${NDIM}.o				\
	tbox__List-hier__Index-NDIM${NDIM}.o				\
	tbox__List-hier__IntVector-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BasePatchHierarchy-NDIM${NDIM}.o		\
	tbox__Pointer-hier__BasePatchLevel-NDIM${NDIM}.o		\
	tbox__Pointer-hier__BinaryTree-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxGeometry-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxGraph-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxList-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxOverlap-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxTop-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxTree-NDIM${NDIM}.o			\
	tbox__Pointer-hier__BoxTreeNode-NDIM${NDIM}.o			\
	tbox__Pointer-hier__CoarseFineBoundary-NDIM${NDIM}.o		\
	tbox__Pointer-hier__GridGeometry-NDIM${NDIM}.o			\
	tbox__Pointer-hier__Index-NDIM${NDIM}.o				\
	tbox__Pointer-hier__LocallyActiveDataPatchLevelManager-NDIM${NDIM}.o\
	tbox__Pointer-hier__MultiblockGridGeometry-NDIM${NDIM}.o	\
	tbox__Pointer-hier__MultiblockPatchHierarchy-NDIM${NDIM}.o	\
	tbox__Pointer-hier__MultiblockPatchLevel-NDIM${NDIM}.o		\
	tbox__Pointer-hier__Patch-NDIM${NDIM}.o				\
	tbox__Pointer-hier__PatchConfigurationUtilities-NDIM${NDIM}.o	\
	tbox__Pointer-hier__PatchData-NDIM${NDIM}.o			\
	tbox__Pointer-hier__PatchDataFactory-NDIM${NDIM}.o		\
	tbox__Pointer-hier__PatchDescriptor-NDIM${NDIM}.o		\
	tbox__Pointer-hier__PatchFactory-NDIM${NDIM}.o			\
	tbox__Pointer-hier__PatchGeometry-NDIM${NDIM}.o			\
	tbox__Pointer-hier__PatchHierarchy-NDIM${NDIM}.o		\
	tbox__Pointer-hier__PatchLevel-NDIM${NDIM}.o			\
	tbox__Pointer-hier__PatchLevelFactory-NDIM${NDIM}.o		\
	tbox__Pointer-hier__Variable-NDIM${NDIM}.o			\
	tbox__Array-tbox__Array-hier__BoundaryBox-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-hier__Box-NDIM${NDIM}.o			\
	tbox__Array-tbox__Array-hier__BoxArray-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-hier__BoxList-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-hier__CoarseFineBoundary-NDIM${NDIM}.o	\
	tbox__Array-tbox__Array-hier__Index-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-hier__IntVector-NDIM${NDIM}.o		\
	tbox__Array-tbox__List-hier__IntVector-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-hier__BoxOverlap-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-hier__BoxTree-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-hier__GridGeometry-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-hier__Index-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-hier__LocallyActiveDataPatchLevelManager-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-hier__MultiblockPatchLevel-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-hier__Patch-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-hier__PatchConfigurationUtilities-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-hier__PatchData-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-hier__PatchDataFactory-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-hier__PatchHierarchy-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-hier__PatchLevel-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-hier__Variable-NDIM${NDIM}.o		\
	tbox__List-tbox__Pointer-hier__Variable-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-tbox__Array-hier__BoundaryBox-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Pointer-hier__MultiblockPatchLevel-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Pointer-hier__PatchLevel-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Array-tbox__Pointer-hier__PatchLevel-NDIM${NDIM}.o


libchar:	


libbool:	


libfloat:	


libdcomplex:	
