//
// File:	MBUtilities-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MBUtilities.h"
#include "MBUtilities.C"

namespace SAMRAI {
   namespace hier {
template class MBUtilities< NDIM >;
}
}
