//
// File:	PatchDescriptor-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchDescriptor.h"
#include "PatchDescriptor.C"

namespace SAMRAI {
   namespace hier {
template class PatchDescriptor< NDIM >;
}
}
