//
// File:	PatchLevel-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchLevel.h"
#include "PatchLevel.C"

namespace SAMRAI {
   namespace hier {
template class PatchLevel< NDIM >;
template class PatchLevelIterator< NDIM >;
}
}
