//
// File:	PatchFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchFactory.h"
#include "PatchFactory.C"

namespace SAMRAI {
   namespace hier {
template class PatchFactory< NDIM >;
}
}
