//
// File:	tbox__Array-tbox__List-hier__MultiblockPatchHierarchy_NDIM___NeighborX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/List.h"
#include "MultiblockPatchHierarchy.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::List< hier::MultiblockPatchHierarchy<NDIM>::Neighbor > >;
}
}
