//
// File:	tbox__List-hier__MultiblockPatchHierarchy_NDIM___NeighborX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "MultiblockPatchHierarchy.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< hier::MultiblockPatchHierarchy<NDIM>::Neighbor > *tbox::ListNode< hier::MultiblockPatchHierarchy<NDIM>::Neighbor >::s_free_list=0;
bool tbox::ListNode< hier::MultiblockPatchHierarchy<NDIM>::Neighbor >::s_registered_callback=false;
#endif
template class tbox::List< hier::MultiblockPatchHierarchy<NDIM>::Neighbor >;
template class tbox::ListIterator< hier::MultiblockPatchHierarchy<NDIM>::Neighbor >;
template class tbox::ListNode< hier::MultiblockPatchHierarchy<NDIM>::Neighbor >;
}
}
