//
// File:	tbox__List-tbox__Pointer-hier__Variable-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "tbox/Pointer.h"
#include "Variable.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< tbox::Pointer< hier::Variable< NDIM > > > *tbox::ListNode< tbox::Pointer< hier::Variable< NDIM > > >::s_free_list=0;
bool tbox::ListNode< tbox::Pointer< hier::Variable< NDIM > > >::s_registered_callback=false;
#endif
template class tbox::List< tbox::Pointer< hier::Variable< NDIM > > >;
template class tbox::ListIterator< tbox::Pointer< hier::Variable< NDIM > > >;
template class tbox::ListNode< tbox::Pointer< hier::Variable< NDIM > > >;
}
}
