//
// File:	tbox__List-hier__BoundaryBox-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "BoundaryBox.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< hier::BoundaryBox< NDIM > > *tbox::ListNode< hier::BoundaryBox< NDIM > >::s_free_list=0;
bool tbox::ListNode< hier::BoundaryBox< NDIM > >::s_registered_callback=false;
#endif
template class tbox::List< hier::BoundaryBox< NDIM > >;
template class tbox::ListIterator< hier::BoundaryBox< NDIM > >;
template class tbox::ListNode< hier::BoundaryBox< NDIM > >;
}
}
