//
// File:	tbox__Array-hier__PatchConfigurationUtilities_NDIM___NeighborPatchInfoX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "PatchConfigurationUtilities.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< hier::PatchConfigurationUtilities<NDIM>::NeighborPatchInfo >;
}
}
