//
// File:	tbox__Array-hier__ComponentSelector.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "ComponentSelector.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< hier::ComponentSelector >;
}
}
