//
// File:	tbox__List-hier__BoxTreeNode_NDIM___TripleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "BoxTreeNode.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< hier::BoxTreeNode<NDIM>::Triple > *tbox::ListNode< hier::BoxTreeNode<NDIM>::Triple >::s_free_list=0;
bool tbox::ListNode< hier::BoxTreeNode<NDIM>::Triple >::s_registered_callback=false;
#endif
template class tbox::List< hier::BoxTreeNode<NDIM>::Triple >;
template class tbox::ListIterator< hier::BoxTreeNode<NDIM>::Triple >;
template class tbox::ListNode< hier::BoxTreeNode<NDIM>::Triple >;
}
}
