//
// File:	tbox__Array-hier__BinaryTree_NDIM___binTreeNodeX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "BinaryTree.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< hier::BinaryTree<NDIM>::binTreeNode >;
}
}
