//
// File:	Variable-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "Variable.h"
#include "Variable.C"

namespace SAMRAI {
   namespace hier {
template class Variable< NDIM >;
}
}
