//
// File:	CellIntegerConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellIntegerConstantRefine.h"
#include "CellIntegerConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class CellIntegerConstantRefine< NDIM >;
}
}
