//
// File:	CellFloatConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellFloatConstantRefine.h"
#include "CellFloatConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class CellFloatConstantRefine< NDIM >;
}
}
