//
// File:	CellIndex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellIndex.h"
#include "CellIndex.C"

namespace SAMRAI {
   namespace pdat {
template class CellIndex< NDIM >;
}
}
