//
// File:	CellFloatLinearTimeInterpolateOp-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellFloatLinearTimeInterpolateOp.h"
#include "CellFloatLinearTimeInterpolateOp.C"

namespace SAMRAI {
   namespace pdat {
template class CellFloatLinearTimeInterpolateOp< NDIM >;
}
}
