//
// File:	EdgeIntegerConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "EdgeIntegerConstantRefine.h"
#include "EdgeIntegerConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class EdgeIntegerConstantRefine< NDIM >;
}
}
