//
// File:	FaceFloatConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceFloatConstantRefine.h"
#include "FaceFloatConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class FaceFloatConstantRefine< NDIM >;
}
}
