//
// File:	FaceOverlap-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceOverlap.h"
#include "FaceOverlap.C"

namespace SAMRAI {
   namespace pdat {
template class FaceOverlap< NDIM >;
}
}
