//
// File:	FaceIntegerConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceIntegerConstantRefine.h"
#include "FaceIntegerConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class FaceIntegerConstantRefine< NDIM >;
}
}
