//
// File:	FaceGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceGeometry.h"
#include "FaceGeometry.C"

namespace SAMRAI {
   namespace pdat {
template class FaceGeometry< NDIM >;
}
}
