//
// File:	FaceDoubleLinearTimeInterpolateOp-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceDoubleLinearTimeInterpolateOp.h"
#include "FaceDoubleLinearTimeInterpolateOp.C"

namespace SAMRAI {
   namespace pdat {
template class FaceDoubleLinearTimeInterpolateOp< NDIM >;
}
}
