##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	ArrayDataIterator-NDIM${NDIM}.o					\
	CellDoubleConstantRefine-NDIM${NDIM}.o				\
	CellDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	CellGeometry-NDIM${NDIM}.o CellIndex-NDIM${NDIM}.o		\
	CellIntegerConstantRefine-NDIM${NDIM}.o				\
	CellIterator-NDIM${NDIM}.o CellOverlap-NDIM${NDIM}.o		\
	EdgeDoubleConstantRefine-NDIM${NDIM}.o				\
	EdgeDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	EdgeGeometry-NDIM${NDIM}.o EdgeIndex-NDIM${NDIM}.o		\
	EdgeIntegerConstantRefine-NDIM${NDIM}.o				\
	EdgeIterator-NDIM${NDIM}.o EdgeOverlap-NDIM${NDIM}.o		\
	FaceDoubleConstantRefine-NDIM${NDIM}.o				\
	FaceDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	FaceGeometry-NDIM${NDIM}.o FaceIndex-NDIM${NDIM}.o		\
	FaceIntegerConstantRefine-NDIM${NDIM}.o				\
	FaceIterator-NDIM${NDIM}.o FaceOverlap-NDIM${NDIM}.o		\
	FirstLayerCellFillPattern-NDIM${NDIM}.o				\
	FirstLayerCellNoCornersFillPattern-NDIM${NDIM}.o		\
	FirstLayerNodeFillPattern-NDIM${NDIM}.o				\
	NodeDoubleInjection-NDIM${NDIM}.o				\
	NodeDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	NodeGeometry-NDIM${NDIM}.o NodeIndex-NDIM${NDIM}.o		\
	NodeIntegerInjection-NDIM${NDIM}.o NodeIterator-NDIM${NDIM}.o	\
	NodeOverlap-NDIM${NDIM}.o OuteredgeGeometry-NDIM${NDIM}.o	\
	OuterfaceDoubleConstantRefine-NDIM${NDIM}.o			\
	OuterfaceDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	OuterfaceGeometry-NDIM${NDIM}.o					\
	OuterfaceIntegerConstantRefine-NDIM${NDIM}.o			\
	OuternodeDoubleConstantCoarsen-NDIM${NDIM}.o			\
	OuternodeGeometry-NDIM${NDIM}.o					\
	OutersideDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	OutersideGeometry-NDIM${NDIM}.o					\
	SecondLayerNodeFillPattern-NDIM${NDIM}.o			\
	SecondLayerNodeNoCornersFillPattern-NDIM${NDIM}.o		\
	SideDoubleConstantRefine-NDIM${NDIM}.o				\
	SideDoubleLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	SideGeometry-NDIM${NDIM}.o SideIndex-NDIM${NDIM}.o		\
	SideIntegerConstantRefine-NDIM${NDIM}.o				\
	SideIterator-NDIM${NDIM}.o SideOverlap-NDIM${NDIM}.o		\
	pdat__ArrayData-NDIM_double${NDIM}.o				\
	pdat__ArrayData-NDIM_int${NDIM}.o				\
	pdat__CellData-NDIM_double${NDIM}.o				\
	pdat__CellData-NDIM_double${NDIM}.o				\
	pdat__CellData-NDIM_int${NDIM}.o				\
	pdat__CellData-NDIM_int${NDIM}.o				\
	pdat__CellDataFactory-NDIM_double${NDIM}.o			\
	pdat__CellDataFactory-NDIM_int${NDIM}.o				\
	pdat__CellVariable-NDIM_double${NDIM}.o				\
	pdat__CellVariable-NDIM_int${NDIM}.o				\
	pdat__EdgeData-NDIM_double${NDIM}.o				\
	pdat__EdgeData-NDIM_int${NDIM}.o				\
	pdat__EdgeDataFactory-NDIM_double${NDIM}.o			\
	pdat__EdgeDataFactory-NDIM_int${NDIM}.o				\
	pdat__EdgeVariable-NDIM_double${NDIM}.o				\
	pdat__EdgeVariable-NDIM_int${NDIM}.o				\
	pdat__FaceData-NDIM_double${NDIM}.o				\
	pdat__FaceData-NDIM_int${NDIM}.o				\
	pdat__FaceDataFactory-NDIM_double${NDIM}.o			\
	pdat__FaceDataFactory-NDIM_int${NDIM}.o				\
	pdat__FaceVariable-NDIM_double${NDIM}.o				\
	pdat__FaceVariable-NDIM_int${NDIM}.o				\
	pdat__MBDataUtilities-NDIM_double${NDIM}.o			\
	pdat__MBDataUtilities-NDIM_int${NDIM}.o				\
	pdat__MultiblockCellDataTranslator-NDIM_double${NDIM}.o		\
	pdat__MultiblockCellDataTranslator-NDIM_int${NDIM}.o		\
	pdat__MultiblockEdgeDataTranslator-NDIM_double${NDIM}.o		\
	pdat__MultiblockEdgeDataTranslator-NDIM_int${NDIM}.o		\
	pdat__MultiblockFaceDataTranslator-NDIM_double${NDIM}.o		\
	pdat__MultiblockFaceDataTranslator-NDIM_int${NDIM}.o		\
	pdat__MultiblockNodeDataTranslator-NDIM_double${NDIM}.o		\
	pdat__MultiblockNodeDataTranslator-NDIM_int${NDIM}.o		\
	pdat__MultiblockSideDataTranslator-NDIM_double${NDIM}.o		\
	pdat__MultiblockSideDataTranslator-NDIM_int${NDIM}.o		\
	pdat__NodeData-NDIM_double${NDIM}.o				\
	pdat__NodeData-NDIM_int${NDIM}.o				\
	pdat__NodeDataFactory-NDIM_double${NDIM}.o			\
	pdat__NodeDataFactory-NDIM_int${NDIM}.o				\
	pdat__NodeVariable-NDIM_double${NDIM}.o				\
	pdat__NodeVariable-NDIM_int${NDIM}.o				\
	pdat__OuteredgeData-NDIM_double${NDIM}.o			\
	pdat__OuteredgeData-NDIM_int${NDIM}.o				\
	pdat__OuteredgeDataFactory-NDIM_double${NDIM}.o			\
	pdat__OuteredgeDataFactory-NDIM_int${NDIM}.o			\
	pdat__OuteredgeVariable-NDIM_double${NDIM}.o			\
	pdat__OuteredgeVariable-NDIM_int${NDIM}.o			\
	pdat__OuterfaceData-NDIM_double${NDIM}.o			\
	pdat__OuterfaceData-NDIM_int${NDIM}.o				\
	pdat__OuterfaceDataFactory-NDIM_double${NDIM}.o			\
	pdat__OuterfaceDataFactory-NDIM_int${NDIM}.o			\
	pdat__OuterfaceVariable-NDIM_double${NDIM}.o			\
	pdat__OuterfaceVariable-NDIM_int${NDIM}.o			\
	pdat__OuternodeData-NDIM_double${NDIM}.o			\
	pdat__OuternodeData-NDIM_int${NDIM}.o				\
	pdat__OuternodeDataFactory-NDIM_double${NDIM}.o			\
	pdat__OuternodeDataFactory-NDIM_int${NDIM}.o			\
	pdat__OuternodeVariable-NDIM_double${NDIM}.o			\
	pdat__OuternodeVariable-NDIM_int${NDIM}.o			\
	pdat__OutersideData-NDIM_double${NDIM}.o			\
	pdat__OutersideData-NDIM_int${NDIM}.o				\
	pdat__OutersideDataFactory-NDIM_double${NDIM}.o			\
	pdat__OutersideDataFactory-NDIM_int${NDIM}.o			\
	pdat__OutersideVariable-NDIM_double${NDIM}.o			\
	pdat__OutersideVariable-NDIM_int${NDIM}.o			\
	pdat__SideData-NDIM_double${NDIM}.o				\
	pdat__SideData-NDIM_int${NDIM}.o				\
	pdat__SideDataFactory-NDIM_double${NDIM}.o			\
	pdat__SideDataFactory-NDIM_int${NDIM}.o				\
	pdat__SideVariable-NDIM_double${NDIM}.o				\
	pdat__SideVariable-NDIM_int${NDIM}.o				\
	pdat__ArrayDataOperationUtilities-NDIM_double_CopyOperation-double${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_double_SumOperation-double${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_int_CopyOperation-int${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_int_SumOperation-int${NDIM}.o\
	tbox__Pointer-pdat__ArrayData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__ArrayData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__CellData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__CellData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__CellDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__CellDataFactory-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__CellDoubleConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__CellIntegerConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__CellVariable-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__CellVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__EdgeData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__EdgeData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__EdgeDoubleConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__EdgeIntegerConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__EdgeVariable-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__EdgeVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__FaceData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__FaceData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__FaceDoubleConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__FaceIntegerConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__FaceVariable-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__FaceVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__FirstLayerCellFillPattern-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__FirstLayerCellNoCornersFillPattern-NDIM${NDIM}.o\
	tbox__Pointer-pdat__FirstLayerNodeFillPattern-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__NodeData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__NodeData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__NodeDoubleInjection-NDIM${NDIM}.o		\
	tbox__Pointer-pdat__NodeIntegerInjection-NDIM${NDIM}.o		\
	tbox__Pointer-pdat__NodeVariable-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__NodeVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_int${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceData-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_int${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceDoubleConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceIntegerConstantRefine-NDIM${NDIM}.o\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeData-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_int${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeDoubleConstantCoarsen-NDIM${NDIM}.o\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OutersideData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__OutersideData-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_int${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__SecondLayerNodeFillPattern-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__SecondLayerNodeNoCornersFillPattern-NDIM${NDIM}.o\
	tbox__Pointer-pdat__SideData-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__SideData-NDIM_int${NDIM}.o			\
	tbox__Pointer-pdat__SideDataFactory-NDIM_double${NDIM}.o	\
	tbox__Pointer-pdat__SideDataFactory-NDIM_int${NDIM}.o		\
	tbox__Pointer-pdat__SideDoubleConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__SideIntegerConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__SideVariable-NDIM_double${NDIM}.o		\
	tbox__Pointer-pdat__SideVariable-NDIM_int${NDIM}.o		\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_double${NDIM}.o	\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_int${NDIM}.o


libchar:	pdat__ArrayData-NDIM_char${NDIM}.o				\
	pdat__CellData-NDIM_char${NDIM}.o				\
	pdat__CellData-NDIM_char${NDIM}.o				\
	pdat__CellDataFactory-NDIM_char${NDIM}.o			\
	pdat__CellVariable-NDIM_char${NDIM}.o				\
	pdat__EdgeData-NDIM_char${NDIM}.o				\
	pdat__EdgeDataFactory-NDIM_char${NDIM}.o			\
	pdat__EdgeVariable-NDIM_char${NDIM}.o				\
	pdat__FaceData-NDIM_char${NDIM}.o				\
	pdat__FaceDataFactory-NDIM_char${NDIM}.o			\
	pdat__FaceVariable-NDIM_char${NDIM}.o				\
	pdat__NodeData-NDIM_char${NDIM}.o				\
	pdat__NodeDataFactory-NDIM_char${NDIM}.o			\
	pdat__NodeVariable-NDIM_char${NDIM}.o				\
	pdat__OuteredgeData-NDIM_char${NDIM}.o				\
	pdat__OuteredgeDataFactory-NDIM_char${NDIM}.o			\
	pdat__OuteredgeVariable-NDIM_char${NDIM}.o			\
	pdat__OuterfaceData-NDIM_char${NDIM}.o				\
	pdat__OuterfaceDataFactory-NDIM_char${NDIM}.o			\
	pdat__OuterfaceVariable-NDIM_char${NDIM}.o			\
	pdat__OuternodeData-NDIM_char${NDIM}.o				\
	pdat__OuternodeDataFactory-NDIM_char${NDIM}.o			\
	pdat__OuternodeVariable-NDIM_char${NDIM}.o			\
	pdat__OutersideData-NDIM_char${NDIM}.o				\
	pdat__OutersideDataFactory-NDIM_char${NDIM}.o			\
	pdat__OutersideVariable-NDIM_char${NDIM}.o			\
	pdat__SideData-NDIM_char${NDIM}.o				\
	pdat__SideDataFactory-NDIM_char${NDIM}.o			\
	pdat__SideVariable-NDIM_char${NDIM}.o				\
	pdat__ArrayDataOperationUtilities-NDIM_char_CopyOperation-char${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_char_SumOperation-char${NDIM}.o\
	tbox__Pointer-pdat__ArrayData-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__CellData-NDIM_char${NDIM}.o			\
	tbox__Pointer-pdat__CellDataFactory-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__CellVariable-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__EdgeData-NDIM_char${NDIM}.o			\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__EdgeVariable-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__FaceData-NDIM_char${NDIM}.o			\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__FaceVariable-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__NodeData-NDIM_char${NDIM}.o			\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__NodeVariable-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceData-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeData-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OutersideData-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_char${NDIM}.o	\
	tbox__Pointer-pdat__SideData-NDIM_char${NDIM}.o			\
	tbox__Pointer-pdat__SideDataFactory-NDIM_char${NDIM}.o		\
	tbox__Pointer-pdat__SideVariable-NDIM_char${NDIM}.o		\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_char${NDIM}.o


libbool:	pdat__ArrayData-NDIM_bool${NDIM}.o				\
	pdat__CellData-NDIM_bool${NDIM}.o				\
	pdat__CellData-NDIM_bool${NDIM}.o				\
	pdat__CellDataFactory-NDIM_bool${NDIM}.o			\
	pdat__CellVariable-NDIM_bool${NDIM}.o				\
	pdat__EdgeData-NDIM_bool${NDIM}.o				\
	pdat__EdgeDataFactory-NDIM_bool${NDIM}.o			\
	pdat__EdgeVariable-NDIM_bool${NDIM}.o				\
	pdat__FaceData-NDIM_bool${NDIM}.o				\
	pdat__FaceDataFactory-NDIM_bool${NDIM}.o			\
	pdat__FaceVariable-NDIM_bool${NDIM}.o				\
	pdat__MBDataUtilities-NDIM_bool${NDIM}.o			\
	pdat__MultiblockCellDataTranslator-NDIM_bool${NDIM}.o		\
	pdat__MultiblockEdgeDataTranslator-NDIM_bool${NDIM}.o		\
	pdat__MultiblockFaceDataTranslator-NDIM_bool${NDIM}.o		\
	pdat__MultiblockNodeDataTranslator-NDIM_bool${NDIM}.o		\
	pdat__MultiblockSideDataTranslator-NDIM_bool${NDIM}.o		\
	pdat__NodeData-NDIM_bool${NDIM}.o				\
	pdat__NodeDataFactory-NDIM_bool${NDIM}.o			\
	pdat__NodeVariable-NDIM_bool${NDIM}.o				\
	pdat__OuteredgeData-NDIM_bool${NDIM}.o				\
	pdat__OuteredgeDataFactory-NDIM_bool${NDIM}.o			\
	pdat__OuteredgeVariable-NDIM_bool${NDIM}.o			\
	pdat__OuterfaceData-NDIM_bool${NDIM}.o				\
	pdat__OuterfaceDataFactory-NDIM_bool${NDIM}.o			\
	pdat__OuterfaceVariable-NDIM_bool${NDIM}.o			\
	pdat__OuternodeData-NDIM_bool${NDIM}.o				\
	pdat__OuternodeDataFactory-NDIM_bool${NDIM}.o			\
	pdat__OuternodeVariable-NDIM_bool${NDIM}.o			\
	pdat__OutersideData-NDIM_bool${NDIM}.o				\
	pdat__OutersideDataFactory-NDIM_bool${NDIM}.o			\
	pdat__OutersideVariable-NDIM_bool${NDIM}.o			\
	pdat__SideData-NDIM_bool${NDIM}.o				\
	pdat__SideDataFactory-NDIM_bool${NDIM}.o			\
	pdat__SideVariable-NDIM_bool${NDIM}.o				\
	pdat__ArrayDataOperationUtilities-NDIM_bool_CopyOperation-bool${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_bool_SumOperation-bool${NDIM}.o\
	tbox__Pointer-pdat__ArrayData-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__CellData-NDIM_bool${NDIM}.o			\
	tbox__Pointer-pdat__CellDataFactory-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__CellVariable-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__EdgeData-NDIM_bool${NDIM}.o			\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__EdgeVariable-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__FaceData-NDIM_bool${NDIM}.o			\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__FaceVariable-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__NodeData-NDIM_bool${NDIM}.o			\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__NodeVariable-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceData-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeData-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OutersideData-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_bool${NDIM}.o	\
	tbox__Pointer-pdat__SideData-NDIM_bool${NDIM}.o			\
	tbox__Pointer-pdat__SideDataFactory-NDIM_bool${NDIM}.o		\
	tbox__Pointer-pdat__SideVariable-NDIM_bool${NDIM}.o		\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_bool${NDIM}.o


libfloat:	CellFloatConstantRefine-NDIM${NDIM}.o				\
	CellFloatLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	EdgeFloatConstantRefine-NDIM${NDIM}.o				\
	EdgeFloatLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	FaceFloatConstantRefine-NDIM${NDIM}.o				\
	FaceFloatLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	NodeFloatInjection-NDIM${NDIM}.o				\
	NodeFloatLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	OuterfaceFloatConstantRefine-NDIM${NDIM}.o			\
	OuterfaceFloatLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	OutersideFloatLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	SideFloatConstantRefine-NDIM${NDIM}.o				\
	SideFloatLinearTimeInterpolateOp-NDIM${NDIM}.o			\
	pdat__ArrayData-NDIM_float${NDIM}.o				\
	pdat__CellData-NDIM_float${NDIM}.o				\
	pdat__CellData-NDIM_float${NDIM}.o				\
	pdat__CellDataFactory-NDIM_float${NDIM}.o			\
	pdat__CellVariable-NDIM_float${NDIM}.o				\
	pdat__EdgeData-NDIM_float${NDIM}.o				\
	pdat__EdgeDataFactory-NDIM_float${NDIM}.o			\
	pdat__EdgeVariable-NDIM_float${NDIM}.o				\
	pdat__FaceData-NDIM_float${NDIM}.o				\
	pdat__FaceDataFactory-NDIM_float${NDIM}.o			\
	pdat__FaceVariable-NDIM_float${NDIM}.o				\
	pdat__MBDataUtilities-NDIM_float${NDIM}.o			\
	pdat__MultiblockCellDataTranslator-NDIM_float${NDIM}.o		\
	pdat__MultiblockEdgeDataTranslator-NDIM_float${NDIM}.o		\
	pdat__MultiblockFaceDataTranslator-NDIM_float${NDIM}.o		\
	pdat__MultiblockNodeDataTranslator-NDIM_float${NDIM}.o		\
	pdat__MultiblockSideDataTranslator-NDIM_float${NDIM}.o		\
	pdat__NodeData-NDIM_float${NDIM}.o				\
	pdat__NodeDataFactory-NDIM_float${NDIM}.o			\
	pdat__NodeVariable-NDIM_float${NDIM}.o				\
	pdat__OuteredgeData-NDIM_float${NDIM}.o				\
	pdat__OuteredgeDataFactory-NDIM_float${NDIM}.o			\
	pdat__OuteredgeVariable-NDIM_float${NDIM}.o			\
	pdat__OuterfaceData-NDIM_float${NDIM}.o				\
	pdat__OuterfaceDataFactory-NDIM_float${NDIM}.o			\
	pdat__OuterfaceVariable-NDIM_float${NDIM}.o			\
	pdat__OuternodeData-NDIM_float${NDIM}.o				\
	pdat__OuternodeDataFactory-NDIM_float${NDIM}.o			\
	pdat__OuternodeVariable-NDIM_float${NDIM}.o			\
	pdat__OutersideData-NDIM_float${NDIM}.o				\
	pdat__OutersideDataFactory-NDIM_float${NDIM}.o			\
	pdat__OutersideVariable-NDIM_float${NDIM}.o			\
	pdat__SideData-NDIM_float${NDIM}.o				\
	pdat__SideDataFactory-NDIM_float${NDIM}.o			\
	pdat__SideVariable-NDIM_float${NDIM}.o				\
	pdat__ArrayDataOperationUtilities-NDIM_float_CopyOperation-float${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_float_SumOperation-float${NDIM}.o\
	tbox__Pointer-pdat__ArrayData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__CellData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__CellDataFactory-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__CellFloatConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__CellVariable-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__EdgeData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__EdgeFloatConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__EdgeVariable-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__FaceData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__FaceFloatConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__FaceVariable-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__NodeData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__NodeFloatInjection-NDIM${NDIM}.o		\
	tbox__Pointer-pdat__NodeVariable-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceFloatConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OutersideData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_float${NDIM}.o	\
	tbox__Pointer-pdat__SideData-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__SideDataFactory-NDIM_float${NDIM}.o		\
	tbox__Pointer-pdat__SideFloatConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__SideVariable-NDIM_float${NDIM}.o		\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_float${NDIM}.o


libdcomplex:	CellComplexConstantRefine-NDIM${NDIM}.o				\
	CellComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	EdgeComplexConstantRefine-NDIM${NDIM}.o				\
	EdgeComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	FaceComplexConstantRefine-NDIM${NDIM}.o				\
	FaceComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	NodeComplexInjection-NDIM${NDIM}.o				\
	NodeComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	OuterfaceComplexConstantRefine-NDIM${NDIM}.o			\
	OuterfaceComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	OutersideComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	SideComplexConstantRefine-NDIM${NDIM}.o				\
	SideComplexLinearTimeInterpolateOp-NDIM${NDIM}.o		\
	pdat__ArrayData-NDIM_dcomplex${NDIM}.o				\
	pdat__CellData-NDIM_dcomplex${NDIM}.o				\
	pdat__CellData-NDIM_dcomplex${NDIM}.o				\
	pdat__CellDataFactory-NDIM_dcomplex${NDIM}.o			\
	pdat__CellVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__EdgeData-NDIM_dcomplex${NDIM}.o				\
	pdat__EdgeDataFactory-NDIM_dcomplex${NDIM}.o			\
	pdat__EdgeVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__FaceData-NDIM_dcomplex${NDIM}.o				\
	pdat__FaceDataFactory-NDIM_dcomplex${NDIM}.o			\
	pdat__FaceVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__MBDataUtilities-NDIM_dcomplex${NDIM}.o			\
	pdat__MultiblockCellDataTranslator-NDIM_dcomplex${NDIM}.o	\
	pdat__MultiblockEdgeDataTranslator-NDIM_dcomplex${NDIM}.o	\
	pdat__MultiblockFaceDataTranslator-NDIM_dcomplex${NDIM}.o	\
	pdat__MultiblockNodeDataTranslator-NDIM_dcomplex${NDIM}.o	\
	pdat__MultiblockSideDataTranslator-NDIM_dcomplex${NDIM}.o	\
	pdat__NodeData-NDIM_dcomplex${NDIM}.o				\
	pdat__NodeDataFactory-NDIM_dcomplex${NDIM}.o			\
	pdat__NodeVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__OuteredgeData-NDIM_dcomplex${NDIM}.o			\
	pdat__OuteredgeDataFactory-NDIM_dcomplex${NDIM}.o		\
	pdat__OuteredgeVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__OuterfaceData-NDIM_dcomplex${NDIM}.o			\
	pdat__OuterfaceDataFactory-NDIM_dcomplex${NDIM}.o		\
	pdat__OuterfaceVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__OuternodeData-NDIM_dcomplex${NDIM}.o			\
	pdat__OuternodeDataFactory-NDIM_dcomplex${NDIM}.o		\
	pdat__OuternodeVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__OutersideData-NDIM_dcomplex${NDIM}.o			\
	pdat__OutersideDataFactory-NDIM_dcomplex${NDIM}.o		\
	pdat__OutersideVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__SideData-NDIM_dcomplex${NDIM}.o				\
	pdat__SideDataFactory-NDIM_dcomplex${NDIM}.o			\
	pdat__SideVariable-NDIM_dcomplex${NDIM}.o			\
	pdat__ArrayDataOperationUtilities-NDIM_dcomplex_CopyOperation-dcomplex${NDIM}.o\
	pdat__ArrayDataOperationUtilities-NDIM_dcomplex_SumOperation-dcomplex${NDIM}.o\
	tbox__Pointer-pdat__ArrayData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__CellComplexConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__CellData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__CellDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__CellVariable-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__EdgeComplexConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__EdgeData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__EdgeDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__EdgeVariable-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__FaceComplexConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__FaceData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__FaceDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__FaceVariable-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__NodeComplexInjection-NDIM${NDIM}.o		\
	tbox__Pointer-pdat__NodeData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__NodeDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__NodeVariable-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__OuteredgeData-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuteredgeVariable-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceComplexConstantRefine-NDIM${NDIM}.o\
	tbox__Pointer-pdat__OuterfaceData-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuterfaceVariable-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeData-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OuternodeVariable-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OutersideData-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OutersideDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__OutersideVariable-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__SideComplexConstantRefine-NDIM${NDIM}.o	\
	tbox__Pointer-pdat__SideData-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-pdat__SideDataFactory-NDIM_dcomplex${NDIM}.o	\
	tbox__Pointer-pdat__SideVariable-NDIM_dcomplex${NDIM}.o		\
	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_dcomplex${NDIM}.o
