//
// File:	NodeDoubleInjection-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeDoubleInjection.h"
#include "NodeDoubleInjection.C"

namespace SAMRAI {
   namespace pdat {
template class NodeDoubleInjection< NDIM >;
}
}
