//
// File:	NodeIterator-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeIterator.h"
#include "NodeIterator.C"

namespace SAMRAI {
   namespace pdat {
template class NodeIterator< NDIM >;
}
}
