//
// File:	OuterfaceFloatLinearTimeInterpolateOp-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuterfaceFloatLinearTimeInterpolateOp.h"
#include "OuterfaceFloatLinearTimeInterpolateOp.C"

namespace SAMRAI {
   namespace pdat {
template class OuterfaceFloatLinearTimeInterpolateOp< NDIM >;
}
}
