//
// File:	OuterfaceDoubleConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuterfaceDoubleConstantRefine.h"
#include "OuterfaceDoubleConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class OuterfaceDoubleConstantRefine< NDIM >;
}
}
