//
// File:	OuterfaceIntegerConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuterfaceIntegerConstantRefine.h"
#include "OuterfaceIntegerConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class OuterfaceIntegerConstantRefine< NDIM >;
}
}
