//
// File:	OuteredgeGeometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuteredgeGeometry.h"
#include "OuteredgeGeometry.C"

namespace SAMRAI {
   namespace pdat {
template class OuteredgeGeometry< NDIM >;
}
}
