//
// File:	OuterfaceDoubleLinearTimeInterpolateOp-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuterfaceDoubleLinearTimeInterpolateOp.h"
#include "OuterfaceDoubleLinearTimeInterpolateOp.C"

namespace SAMRAI {
   namespace pdat {
template class OuterfaceDoubleLinearTimeInterpolateOp< NDIM >;
}
}
