//
// File:	pdat__FaceVariable-NDIM_charX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceVariable.h"
#include "FaceVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::FaceVariable< NDIM,char >;
}
}
