//
// File:	pdat__ArrayDataOperationUtilities-NDIM_bool_SumOperation-boolX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ArrayDataOperationUtilities.h"
#include "ArrayDataOperationUtilities.C"
#include "SumOperation.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::ArrayDataOperationUtilities< NDIM,bool,SumOperation< bool > >;
}
}
