//
// File:	pdat__OuteredgeVariable-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuteredgeVariable.h"
#include "OuteredgeVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::OuteredgeVariable< NDIM,int >;
}
}
