//
// File:	pdat__OuternodeVariable-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuternodeVariable.h"
#include "OuternodeVariable.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::OuternodeVariable< NDIM,dcomplex >;
}
}
