//
// File:	pdat__SideVariable-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SideVariable.h"
#include "SideVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::SideVariable< NDIM,double >;
}
}
