//
// File:	pdat__FaceData-NDIM_boolX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "FaceData.h"
#include "FaceData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::FaceData< NDIM,bool >;
}
}
