//
// File:	pdat__MultiblockNodeDataTranslator-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockNodeDataTranslator.h"
#include "MultiblockNodeDataTranslator.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::MultiblockNodeDataTranslator< NDIM,float >;
}
}
