//
// File:	pdat__ArrayDataOperationUtilities-NDIM_dcomplex_SumOperation-dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ArrayDataOperationUtilities.h"
#include "ArrayDataOperationUtilities.C"
#include "tbox/Complex.h"
#include "SumOperation.h"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::ArrayDataOperationUtilities< NDIM,dcomplex,SumOperation< dcomplex > >;
}
}
