//
// File:	pdat__OutersideData-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OutersideData.h"
#include "OutersideData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::OutersideData< NDIM,double >;
}
}
