//
// File:	pdat__MultiblockSideDataTranslator-NDIM_boolX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockSideDataTranslator.h"
#include "MultiblockSideDataTranslator.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::MultiblockSideDataTranslator< NDIM,bool >;
}
}
