//
// File:	pdat__OuteredgeData-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuteredgeData.h"
#include "OuteredgeData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::OuteredgeData< NDIM,int >;
}
}
