//
// File:	pdat__EdgeDataFactory-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "EdgeDataFactory.h"
#include "EdgeDataFactory.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::EdgeDataFactory< NDIM,dcomplex >;
}
}
