//
// File:	pdat__CellVariable-NDIM_charX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellVariable.h"
#include "CellVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::CellVariable< NDIM,char >;
}
}
