//
// File:	pdat__NodeVariable-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeVariable.h"
#include "NodeVariable.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::NodeVariable< NDIM,dcomplex >;
}
}
