//
// File:	pdat__OuterfaceVariable-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuterfaceVariable.h"
#include "OuterfaceVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::OuterfaceVariable< NDIM,int >;
}
}
