//
// File:	pdat__NodeDataFactory-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "NodeDataFactory.h"
#include "NodeDataFactory.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::NodeDataFactory< NDIM,double >;
}
}
