//
// File:	pdat__EdgeDataFactory-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "EdgeDataFactory.h"
#include "EdgeDataFactory.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::EdgeDataFactory< NDIM,int >;
}
}
