//
// File:	pdat__MBDataUtilities-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MBDataUtilities.h"
#include "MBDataUtilities.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::MBDataUtilities< NDIM,double >;
}
}
