//
// File:	pdat__CellDataFactory-NDIM_boolX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellDataFactory.h"
#include "CellDataFactory.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::CellDataFactory< NDIM,bool >;
}
}
