//
// File:	pdat__ArrayData-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ArrayData.h"
#include "ArrayData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::ArrayData< NDIM,int >;
}
}
