//
// File:	pdat__OuternodeData-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OuternodeData.h"
#include "OuternodeData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::OuternodeData< NDIM,int >;
}
}
