//
// File:	pdat__OutersideDataFactory-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OutersideDataFactory.h"
#include "OutersideDataFactory.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::OutersideDataFactory< NDIM,dcomplex >;
}
}
