//
// File:	pdat__MultiblockEdgeDataTranslator-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockEdgeDataTranslator.h"
#include "MultiblockEdgeDataTranslator.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::MultiblockEdgeDataTranslator< NDIM,double >;
}
}
