//
// File:	pdat__OutersideData-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "OutersideData.h"
#include "OutersideData.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::OutersideData< NDIM,dcomplex >;
}
}
