//
// File:	pdat__SideDataFactory-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SideDataFactory.h"
#include "SideDataFactory.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::SideDataFactory< NDIM,dcomplex >;
}
}
