//
// File:	pdat__CellData-NDIM_charX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CellData.h"
#include "CellData.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::CellData< NDIM,char >;
}
}
