//
// File:	pdat__SideData-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SideData.h"
#include "SideData.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace pdat {
template class pdat::SideData< NDIM,dcomplex >;
}
}
