//
// File:	pdat__EdgeVariable-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "EdgeVariable.h"
#include "EdgeVariable.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::EdgeVariable< NDIM,float >;
}
}
