//
// File:	pdat__MultiblockCellDataTranslator-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockCellDataTranslator.h"
#include "MultiblockCellDataTranslator.C"

namespace SAMRAI {
   namespace pdat {
template class pdat::MultiblockCellDataTranslator< NDIM,int >;
}
}
