//
// File:	SideDoubleConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SideDoubleConstantRefine.h"
#include "SideDoubleConstantRefine.C"

namespace SAMRAI {
   namespace pdat {
template class SideDoubleConstantRefine< NDIM >;
}
}
