//
// File:	SideDoubleLinearTimeInterpolateOp-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "SideDoubleLinearTimeInterpolateOp.h"
#include "SideDoubleLinearTimeInterpolateOp.C"

namespace SAMRAI {
   namespace pdat {
template class SideDoubleLinearTimeInterpolateOp< NDIM >;
}
}
