//
// File:	tbox__Pointer-pdat__OuterfaceFloatConstantRefine-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "OuterfaceFloatConstantRefine.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< pdat::OuterfaceFloatConstantRefine< NDIM > >;
}
}
