//
// File:	tbox__Pointer-pdat__OuterfaceVariable-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "OuterfaceVariable.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< pdat::OuterfaceVariable< NDIM,int > >;
}
}
