//
// File:	tbox__Pointer-pdat__OuterfaceDataFactory-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "OuterfaceDataFactory.h"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< pdat::OuterfaceDataFactory< NDIM,dcomplex > >;
}
}
