//
// File:	tbox__Array-tbox__Pointer-pdat__ArrayData-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "tbox/Pointer.h"
#include "ArrayData.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< tbox::Pointer< pdat::ArrayData< NDIM,int > > >;
}
}
