#!/bin/sh
# This script is used to start the TCL interpreter running
# the tcl script with the same name as this file.
# 

path=$0
PWD=`pwd`
#
# Resolve symbolic links to find the real home
#
while test -h $path; do              # while $path is a link
  for newpath in `ls -l $path `; do  # get what it links to
    test                             # noop
  done;
  if echo $newpath | grep '^/'; then # if path is absolute
    path=$newpath;                   #   follow link to absolute path
  else                               # else (path is relative)
    relpath=`dirname $newpath`       #   strip the file off the path
    cd $relpath                      #   cd to that directory
    path=`pwd`/`basename $newpath`   #   generate absolute path
  fi
done

cd $PWD                              # cd to original directory
DIR=`dirname $path`                  # find the absolute path where bin/babel is
VTK_INSTALL_PATH=`cd "$DIR/.." && pwd`
export VTK_INSTALL_PATH

# The script name
RUNSCRIPT=`basename $0`.tcl

# Start vizamrai script in backgound 
$VTK_INSTALL_PATH/bin/cvish $VTK_INSTALL_PATH/bin/$RUNSCRIPT $* &





