CC = cc

CFLAGS = -g

INCLUDE = -I. -I/usr/include/ -I/usr/include/X11/ -I/usr/local/include/GL

LDLIBS = -lm -lGL -lpthread -lXext -lX11

LDFLAGS =  -L. -L/usr/lib -L/usr/X11R6/lib -L/usr/local/lib

UNAME=Linux

all: test_for_opengl.$(UNAME)

test_for_opengl.$(UNAME): test_for_opengl.c
	$(CC) $(CFLAGS) $(INCLUDE) test_for_opengl.c $(LDFLAGS) $(LDLIBS) -o $@
