//
// File:	PETScAbstractVectorReal-double.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PETScAbstractVectorReal.h"
#include "PETScAbstractVectorReal.C"

namespace SAMRAI {
   namespace solv {
#ifdef HAVE_PETSC
template class PETScAbstractVectorReal< double >;
#endif
}
}
