#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/source/scripts/change_copyright $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: bash script to update copyright dates in SAMRAI files
##

# Note: this may work with sh but I have not tested it. sh probably
# won't be able to handle a large number of files in the "for"
# statement.

#=============================================================================
# Change the copyright statement in all files which have the date.
#=============================================================================
#
# These are the commands you can use to replace the copyright date
# in all files.
#
# You may want to run each of these commands from the command line to
# make sure things are doing what you think they should be doing.
# (The author does this which is why they are seperated into the 
#  steps, you could make this more efficient).
# 

#=============================================================================
# First find all the files with old copyright dates
#=============================================================================
find . -type f ! -name \*.svn\* -exec grep -l "1997-2008" {} \; > files

#=============================================================================
# Replace the old copyright dates with new dates
#=============================================================================
for i in `cat files`
do
    echo $i
    cp $i $i.sed.bak
    sed "s/1997-2008/1997-2008/" $i.sed.bak > $i
done

#=============================================================================
# Remove the temporary files
#=============================================================================
find . -name \*.sed.bak -exec rm {} \;
rm files
	
