#! /bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/source/scripts/run-after-update $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 2059 $
## Modified:    $LastChangedDate: 2008-03-21 09:43:20 -0700 (Fri, 21 Mar 2008) $
## Description: shell script for misc tasks after updating from repository.
##

# This script may be run after updating from svn to make bring
# the working directory from the svn state to a functional state.
# Nothing mysterious is done.  You can do everything by hand if you
# choose.

# Go to the top level SAMRAI directory and make sure we get there.
cd `dirname $0`/../.. || exit 1;
test -d "source/hierarchy/patches" || exit 1
pwd

# Update the includes directory.
echo "Running the includes script"
perl source/scripts/includes "$@"
