#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/source/scripts/update $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: shell script to run updateXd, include, and depend
##

BIN=`dirname $0`

perl $BIN/updateXd.pl
#NOTE: I removed the "includes" part of this script because it causes a 
#      weird dependency between linked and actual include files.  e.g. if you 
#      run "includes --link" and then run "update" it screws up your include 
#      directory.  AMW 5/05
#perl $BIN/includes "$@"
sh $BIN/depend

if test -n "`pwd | grep ./source/.`" ; then
   echo "Warning - you may need to re-run $BIN/depend in SAMRAI/source..."
fi

exit 0
