#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/source/scripts/update_configure $
## Package:     SAMRAI templates
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: shell script to regenerate configure.
##

# Go to the top level SAMRAI directory and make sure we get there.
cd `dirname $0`/../.. || exit 1;
test -d "source/hierarchy/patches" || exit 1

echo "Checking out acmacros"
cvs -d /usr/casc/samrai/gunney/cvsrepository checkout -rv_0_3 acmacros

echo "Running aclocal"
aclocal -I config -I acmacros --output=config/aclocal.m4

echo "Running autoconf"
autoconf -I config
