#!/bin/sh
##
## File:        $URL: file:///usr/casc/samrai/repository/SAMRAI/tags/v-2-4-4/tools/scripts/conversion2.0/rename_tbox $
## Package:     SAMRAI scripts
## Copyright:   (c) 1997-2008 Lawrence Livermore National Security, LLC
## Revision:    $LastChangedRevision: 1917 $
## Modified:    $LastChangedDate: 2008-01-25 13:28:01 -0800 (Fri, 25 Jan 2008) $
## Description: shell script to run rename X class names to template on <DIM>
##

BIN=`dirname $0`

perl $BIN/rename_tbox.pl tbox_classes

exit

