//
// File:	ArrayDataNormOpsReal-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "ArrayDataNormOpsReal.h"
#include "ArrayDataNormOpsReal.C"

namespace SAMRAI {
   namespace math {
template class ArrayDataNormOpsReal< NDIM,float >;
}
}
