//
// File:	HierarchyNodeDataOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyNodeDataOpsComplex.h"
#include "HierarchyNodeDataOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class HierarchyNodeDataOpsComplex< NDIM >;
}
}
