//
// File:	HierarchyEdgeDataOpsInteger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyEdgeDataOpsInteger.h"
#include "HierarchyEdgeDataOpsInteger.C"

namespace SAMRAI {
   namespace math {
template class HierarchyEdgeDataOpsInteger< NDIM >;
}
}
