//
// File:	HierarchyDataOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyDataOpsReal.h"
#include "HierarchyDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class HierarchyDataOpsReal< NDIM,double >;
}
}
