//
// File:	HierarchySideDataOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchySideDataOpsComplex.h"
#include "HierarchySideDataOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class HierarchySideDataOpsComplex< NDIM >;
}
}
