//
// File:	HierarchyNodeDataOpsInteger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyNodeDataOpsInteger.h"
#include "HierarchyNodeDataOpsInteger.C"

namespace SAMRAI {
   namespace math {
template class HierarchyNodeDataOpsInteger< NDIM >;
}
}
