//
// File:	HierarchyEdgeDataOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyEdgeDataOpsComplex.h"
#include "HierarchyEdgeDataOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class HierarchyEdgeDataOpsComplex< NDIM >;
}
}
