##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	ArrayDataBasicOps-NDIM_double${NDIM}.o				\
	ArrayDataBasicOps-NDIM_int${NDIM}.o				\
	ArrayDataMiscellaneousOpsReal-NDIM_double${NDIM}.o		\
	ArrayDataNormOpsInteger-NDIM${NDIM}.o				\
	ArrayDataNormOpsReal-NDIM_double${NDIM}.o			\
	HierarchyCellDataOpsInteger-NDIM${NDIM}.o			\
	HierarchyDataOpsInteger-NDIM${NDIM}.o				\
	HierarchyDataOpsManager-NDIM${NDIM}.o				\
	HierarchyDataOpsReal-NDIM_double${NDIM}.o			\
	HierarchyEdgeDataOpsInteger-NDIM${NDIM}.o			\
	HierarchyFaceDataOpsInteger-NDIM${NDIM}.o			\
	HierarchyNodeDataOpsInteger-NDIM${NDIM}.o			\
	HierarchySideDataOpsInteger-NDIM${NDIM}.o			\
	PatchCellDataOpsInteger-NDIM${NDIM}.o				\
	PatchEdgeDataOpsInteger-NDIM${NDIM}.o				\
	PatchFaceDataOpsInteger-NDIM${NDIM}.o				\
	PatchNodeDataOpsInteger-NDIM${NDIM}.o				\
	PatchSideDataOpsInteger-NDIM${NDIM}.o				\
	math__HierarchyCellDataOpsReal-NDIM_double${NDIM}.o		\
	math__HierarchyEdgeDataOpsReal-NDIM_double${NDIM}.o		\
	math__HierarchyFaceDataOpsReal-NDIM_double${NDIM}.o		\
	math__HierarchyNodeDataOpsReal-NDIM_double${NDIM}.o		\
	math__HierarchySideDataOpsReal-NDIM_double${NDIM}.o		\
	math__PatchCellDataBasicOps-NDIM_double${NDIM}.o		\
	math__PatchCellDataBasicOps-NDIM_int${NDIM}.o			\
	math__PatchCellDataMiscellaneousOpsReal-NDIM_double${NDIM}.o	\
	math__PatchCellDataNormOpsReal-NDIM_double${NDIM}.o		\
	math__PatchCellDataOpsReal-NDIM_double${NDIM}.o			\
	math__PatchEdgeDataBasicOps-NDIM_double${NDIM}.o		\
	math__PatchEdgeDataBasicOps-NDIM_int${NDIM}.o			\
	math__PatchEdgeDataMiscellaneousOpsReal-NDIM_double${NDIM}.o	\
	math__PatchEdgeDataNormOpsReal-NDIM_double${NDIM}.o		\
	math__PatchEdgeDataOpsReal-NDIM_double${NDIM}.o			\
	math__PatchFaceDataBasicOps-NDIM_double${NDIM}.o		\
	math__PatchFaceDataBasicOps-NDIM_int${NDIM}.o			\
	math__PatchFaceDataMiscellaneousOpsReal-NDIM_double${NDIM}.o	\
	math__PatchFaceDataNormOpsReal-NDIM_double${NDIM}.o		\
	math__PatchFaceDataOpsReal-NDIM_double${NDIM}.o			\
	math__PatchNodeDataBasicOps-NDIM_double${NDIM}.o		\
	math__PatchNodeDataBasicOps-NDIM_int${NDIM}.o			\
	math__PatchNodeDataMiscellaneousOpsReal-NDIM_double${NDIM}.o	\
	math__PatchNodeDataNormOpsReal-NDIM_double${NDIM}.o		\
	math__PatchNodeDataOpsReal-NDIM_double${NDIM}.o			\
	math__PatchSideDataBasicOps-NDIM_double${NDIM}.o		\
	math__PatchSideDataBasicOps-NDIM_int${NDIM}.o			\
	math__PatchSideDataMiscellaneousOpsReal-NDIM_double${NDIM}.o	\
	math__PatchSideDataNormOpsReal-NDIM_double${NDIM}.o		\
	math__PatchSideDataOpsReal-NDIM_double${NDIM}.o			\
	tbox__Pointer-math__HierarchyCellDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyCellDataOpsReal-NDIM_double${NDIM}.o\
	tbox__Pointer-math__HierarchyDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Pointer-math__HierarchyEdgeDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyEdgeDataOpsReal-NDIM_double${NDIM}.o\
	tbox__Pointer-math__HierarchyFaceDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyFaceDataOpsReal-NDIM_double${NDIM}.o\
	tbox__Pointer-math__HierarchyNodeDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyNodeDataOpsReal-NDIM_double${NDIM}.o\
	tbox__Pointer-math__HierarchySideDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchySideDataOpsReal-NDIM_double${NDIM}.o\
	tbox__Pointer-math__PatchCellDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchCellDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Pointer-math__PatchEdgeDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchEdgeDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Pointer-math__PatchFaceDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchFaceDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Pointer-math__PatchNodeDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchNodeDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Pointer-math__PatchSideDataOpsInteger-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchSideDataOpsReal-NDIM_double${NDIM}.o	\
	tbox__Array-tbox__Pointer-math__HierarchyDataOpsInteger-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-math__HierarchyDataOpsReal-NDIM_double${NDIM}.o


libchar:	


libbool:	


libfloat:	ArrayDataBasicOps-NDIM_float${NDIM}.o				\
	ArrayDataMiscellaneousOpsReal-NDIM_float${NDIM}.o		\
	ArrayDataNormOpsReal-NDIM_float${NDIM}.o			\
	HierarchyDataOpsReal-NDIM_float${NDIM}.o			\
	math__HierarchyCellDataOpsReal-NDIM_float${NDIM}.o		\
	math__HierarchyEdgeDataOpsReal-NDIM_float${NDIM}.o		\
	math__HierarchyFaceDataOpsReal-NDIM_float${NDIM}.o		\
	math__HierarchyNodeDataOpsReal-NDIM_float${NDIM}.o		\
	math__HierarchySideDataOpsReal-NDIM_float${NDIM}.o		\
	math__PatchCellDataBasicOps-NDIM_float${NDIM}.o			\
	math__PatchCellDataMiscellaneousOpsReal-NDIM_float${NDIM}.o	\
	math__PatchCellDataNormOpsReal-NDIM_float${NDIM}.o		\
	math__PatchCellDataOpsReal-NDIM_float${NDIM}.o			\
	math__PatchEdgeDataBasicOps-NDIM_float${NDIM}.o			\
	math__PatchEdgeDataMiscellaneousOpsReal-NDIM_float${NDIM}.o	\
	math__PatchEdgeDataNormOpsReal-NDIM_float${NDIM}.o		\
	math__PatchEdgeDataOpsReal-NDIM_float${NDIM}.o			\
	math__PatchFaceDataBasicOps-NDIM_float${NDIM}.o			\
	math__PatchFaceDataMiscellaneousOpsReal-NDIM_float${NDIM}.o	\
	math__PatchFaceDataNormOpsReal-NDIM_float${NDIM}.o		\
	math__PatchFaceDataOpsReal-NDIM_float${NDIM}.o			\
	math__PatchNodeDataBasicOps-NDIM_float${NDIM}.o			\
	math__PatchNodeDataMiscellaneousOpsReal-NDIM_float${NDIM}.o	\
	math__PatchNodeDataNormOpsReal-NDIM_float${NDIM}.o		\
	math__PatchNodeDataOpsReal-NDIM_float${NDIM}.o			\
	math__PatchSideDataBasicOps-NDIM_float${NDIM}.o			\
	math__PatchSideDataMiscellaneousOpsReal-NDIM_float${NDIM}.o	\
	math__PatchSideDataNormOpsReal-NDIM_float${NDIM}.o		\
	math__PatchSideDataOpsReal-NDIM_float${NDIM}.o			\
	tbox__Pointer-math__HierarchyCellDataOpsReal-NDIM_float${NDIM}.o\
	tbox__Pointer-math__HierarchyDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Pointer-math__HierarchyEdgeDataOpsReal-NDIM_float${NDIM}.o\
	tbox__Pointer-math__HierarchyFaceDataOpsReal-NDIM_float${NDIM}.o\
	tbox__Pointer-math__HierarchyNodeDataOpsReal-NDIM_float${NDIM}.o\
	tbox__Pointer-math__HierarchySideDataOpsReal-NDIM_float${NDIM}.o\
	tbox__Pointer-math__PatchCellDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Pointer-math__PatchEdgeDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Pointer-math__PatchFaceDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Pointer-math__PatchNodeDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Pointer-math__PatchSideDataOpsReal-NDIM_float${NDIM}.o	\
	tbox__Array-tbox__Pointer-math__HierarchyDataOpsReal-NDIM_float${NDIM}.o


libdcomplex:	ArrayDataBasicOps-NDIM_dcomplex${NDIM}.o			\
	ArrayDataNormOpsComplex-NDIM${NDIM}.o				\
	HierarchyCellDataOpsComplex-NDIM${NDIM}.o			\
	HierarchyDataOpsComplex-NDIM${NDIM}.o				\
	HierarchyDataOpsComplex-NDIM${NDIM}.o				\
	HierarchyDataOpsManager-NDIM${NDIM}.o				\
	HierarchyEdgeDataOpsComplex-NDIM${NDIM}.o			\
	HierarchyFaceDataOpsComplex-NDIM${NDIM}.o			\
	HierarchyNodeDataOpsComplex-NDIM${NDIM}.o			\
	HierarchySideDataOpsComplex-NDIM${NDIM}.o			\
	PatchCellDataNormOpsComplex-NDIM${NDIM}.o			\
	PatchCellDataOpsComplex-NDIM${NDIM}.o				\
	PatchEdgeDataNormOpsComplex-NDIM${NDIM}.o			\
	PatchEdgeDataOpsComplex-NDIM${NDIM}.o				\
	PatchFaceDataNormOpsComplex-NDIM${NDIM}.o			\
	PatchFaceDataOpsComplex-NDIM${NDIM}.o				\
	PatchNodeDataNormOpsComplex-NDIM${NDIM}.o			\
	PatchNodeDataOpsComplex-NDIM${NDIM}.o				\
	PatchSideDataNormOpsComplex-NDIM${NDIM}.o			\
	PatchSideDataOpsComplex-NDIM${NDIM}.o				\
	math__PatchCellDataBasicOps-NDIM_dcomplex${NDIM}.o		\
	math__PatchEdgeDataBasicOps-NDIM_dcomplex${NDIM}.o		\
	math__PatchFaceDataBasicOps-NDIM_dcomplex${NDIM}.o		\
	math__PatchNodeDataBasicOps-NDIM_dcomplex${NDIM}.o		\
	math__PatchSideDataBasicOps-NDIM_dcomplex${NDIM}.o		\
	tbox__Pointer-math__HierarchyCellDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyEdgeDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyFaceDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchyNodeDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__HierarchySideDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchCellDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchEdgeDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchFaceDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchNodeDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Pointer-math__PatchSideDataOpsComplex-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-math__HierarchyDataOpsComplex-NDIM${NDIM}.o
