//
// File:	math__HierarchyFaceDataOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyFaceDataOpsReal.h"
#include "HierarchyFaceDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::HierarchyFaceDataOpsReal< NDIM,double >;
}
}
