//
// File:	math__HierarchySideDataOpsReal-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchySideDataOpsReal.h"
#include "HierarchySideDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::HierarchySideDataOpsReal< NDIM,float >;
}
}
