//
// File:	math__PatchSideDataBasicOps-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataBasicOps.h"
#include "PatchSideDataBasicOps.C"

namespace SAMRAI {
   namespace math {
template class math::PatchSideDataBasicOps< NDIM,float >;
}
}
