//
// File:	math__PatchSideDataMiscellaneousOpsReal-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataMiscellaneousOpsReal.h"
#include "PatchSideDataMiscellaneousOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::PatchSideDataMiscellaneousOpsReal< NDIM,float >;
}
}
