//
// File:	math__PatchNodeDataBasicOps-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchNodeDataBasicOps.h"
#include "PatchNodeDataBasicOps.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace math {
template class math::PatchNodeDataBasicOps< NDIM,dcomplex >;
}
}
