//
// File:	math__PatchNodeDataNormOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchNodeDataNormOpsReal.h"
#include "PatchNodeDataNormOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::PatchNodeDataNormOpsReal< NDIM,double >;
}
}
