//
// File:	math__PatchFaceDataBasicOps-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchFaceDataBasicOps.h"
#include "PatchFaceDataBasicOps.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace math {
template class math::PatchFaceDataBasicOps< NDIM,dcomplex >;
}
}
