//
// File:	math__PatchSideDataNormOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataNormOpsReal.h"
#include "PatchSideDataNormOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::PatchSideDataNormOpsReal< NDIM,double >;
}
}
