//
// File:	math__HierarchyCellDataOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyCellDataOpsReal.h"
#include "HierarchyCellDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::HierarchyCellDataOpsReal< NDIM,double >;
}
}
