//
// File:	math__PatchFaceDataBasicOps-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchFaceDataBasicOps.h"
#include "PatchFaceDataBasicOps.C"

namespace SAMRAI {
   namespace math {
template class math::PatchFaceDataBasicOps< NDIM,double >;
}
}
