//
// File:	math__PatchSideDataOpsReal-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataOpsReal.h"
#include "PatchSideDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::PatchSideDataOpsReal< NDIM,float >;
}
}
