//
// File:	math__PatchEdgeDataMiscellaneousOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchEdgeDataMiscellaneousOpsReal.h"
#include "PatchEdgeDataMiscellaneousOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::PatchEdgeDataMiscellaneousOpsReal< NDIM,double >;
}
}
