//
// File:	math__HierarchyNodeDataOpsReal-NDIM_doubleX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "HierarchyNodeDataOpsReal.h"
#include "HierarchyNodeDataOpsReal.C"

namespace SAMRAI {
   namespace math {
template class math::HierarchyNodeDataOpsReal< NDIM,double >;
}
}
