//
// File:	math__PatchEdgeDataBasicOps-NDIM_dcomplexX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchEdgeDataBasicOps.h"
#include "PatchEdgeDataBasicOps.C"
#include "tbox/Complex.h"

namespace SAMRAI {
   namespace math {
template class math::PatchEdgeDataBasicOps< NDIM,dcomplex >;
}
}
