//
// File:	math__PatchEdgeDataBasicOps-NDIM_intX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchEdgeDataBasicOps.h"
#include "PatchEdgeDataBasicOps.C"

namespace SAMRAI {
   namespace math {
template class math::PatchEdgeDataBasicOps< NDIM,int >;
}
}
