//
// File:	PatchSideDataOpsInteger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataOpsInteger.h"
#include "PatchSideDataOpsInteger.C"

namespace SAMRAI {
   namespace math {
template class PatchSideDataOpsInteger< NDIM >;
}
}
