//
// File:	PatchEdgeDataOpsInteger-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchEdgeDataOpsInteger.h"
#include "PatchEdgeDataOpsInteger.C"

namespace SAMRAI {
   namespace math {
template class PatchEdgeDataOpsInteger< NDIM >;
}
}
