//
// File:	PatchCellDataNormOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchCellDataNormOpsComplex.h"
#include "PatchCellDataNormOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class PatchCellDataNormOpsComplex< NDIM >;
}
}
