//
// File:	PatchSideDataOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchSideDataOpsComplex.h"
#include "PatchSideDataOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class PatchSideDataOpsComplex< NDIM >;
}
}
