//
// File:	PatchFaceDataOpsComplex-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "PatchFaceDataOpsComplex.h"
#include "PatchFaceDataOpsComplex.C"

namespace SAMRAI {
   namespace math {
template class PatchFaceDataOpsComplex< NDIM >;
}
}
