//
// File:	tbox__Pointer-math__HierarchySideDataOpsReal-NDIM_floatX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Pointer.h"
#include "tbox/Pointer.C"
#include "HierarchySideDataOpsReal.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Pointer< math::HierarchySideDataOpsReal< NDIM,float > >;
}
}
