//
// File:	tbox__Array-mesh__SpatialKey.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/Array.h"
#include "tbox/Array.C"
#include "SpatialKey.h"

namespace SAMRAI {
   namespace tbox {
template class tbox::Array< mesh::SpatialKey >;
}
}
