//
// File:	CoarsenTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "CoarsenTransactionFactory.h"
#include "CoarsenTransactionFactory.C"

namespace SAMRAI {
   namespace xfer {
template class CoarsenTransactionFactory< NDIM >;
}
}
