//
// File:	Geometry-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "Geometry.h"
#include "Geometry.C"

namespace SAMRAI {
   namespace xfer {
template class Geometry< NDIM >;
}
}
