//
// File:	LocallyActiveDataCoarsenSchedule-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataCoarsenSchedule.h"
#include "LocallyActiveDataCoarsenSchedule.C"

namespace SAMRAI {
   namespace xfer {
template class LocallyActiveDataCoarsenSchedule< NDIM >;
}
}
