//
// File:	LocallyActiveDataRefinePatchStrategy-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataRefinePatchStrategy.h"
#include "LocallyActiveDataRefinePatchStrategy.C"

namespace SAMRAI {
   namespace xfer {
template class LocallyActiveDataRefinePatchStrategy< NDIM >;
}
}
