//
// File:	LocallyActiveDataCoarsenTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "LocallyActiveDataCoarsenTransactionFactory.h"
#include "LocallyActiveDataCoarsenTransactionFactory.C"

namespace SAMRAI {
   namespace xfer {
template class LocallyActiveDataCoarsenTransactionFactory< NDIM >;
}
}
