##
## File:	Makefile.objects
## Package:	SAMRAI
## Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
## Release:	$Name:  $
## Revision:	$Revision: $
## Modified:	$Date: $
## Description:	makefile objects
##



libdefault:	BoxGeometryFillPattern-NDIM${NDIM}.o				\
	CoarsenAlgorithm-NDIM${NDIM}.o CoarsenClasses-NDIM${NDIM}.o	\
	CoarsenCopyTransaction-NDIM${NDIM}.o				\
	CoarsenOperator-NDIM${NDIM}.o CoarsenPatchStrategy-NDIM${NDIM}.o\
	CoarsenSchedule-NDIM${NDIM}.o					\
	CoarsenTransactionFactory-NDIM${NDIM}.o FillBoxSet-NDIM${NDIM}.o\
	Geometry-NDIM${NDIM}.o						\
	LocallyActiveDataCoarsenAlgorithm-NDIM${NDIM}.o			\
	LocallyActiveDataCoarsenPatchStrategy-NDIM${NDIM}.o		\
	LocallyActiveDataCoarsenSchedule-NDIM${NDIM}.o			\
	LocallyActiveDataCoarsenTransactionFactory-NDIM${NDIM}.o	\
	LocallyActiveDataFillBox-NDIM${NDIM}.o				\
	LocallyActiveDataFillBoxSet-NDIM${NDIM}.o			\
	LocallyActiveDataRefineAlgorithm-NDIM${NDIM}.o			\
	LocallyActiveDataRefinePatchStrategy-NDIM${NDIM}.o		\
	LocallyActiveDataRefineSchedule-NDIM${NDIM}.o			\
	LocallyActiveDataRefineTransactionFactory-NDIM${NDIM}.o		\
	MultiblockCoarsenAlgorithm-NDIM${NDIM}.o			\
	MultiblockCoarsenPatchStrategy-NDIM${NDIM}.o			\
	MultiblockCoarsenSchedule-NDIM${NDIM}.o				\
	MultiblockRefineAlgorithm-NDIM${NDIM}.o				\
	MultiblockRefinePatchStrategy-NDIM${NDIM}.o			\
	MultiblockRefineSchedule-NDIM${NDIM}.o				\
	RefineAlgorithm-NDIM${NDIM}.o RefineClasses-NDIM${NDIM}.o	\
	RefineCopyTransaction-NDIM${NDIM}.o RefineOperator-NDIM${NDIM}.o\
	RefinePatchStrategy-NDIM${NDIM}.o RefineSchedule-NDIM${NDIM}.o	\
	RefineTimeTransaction-NDIM${NDIM}.o				\
	RefineTransactionFactory-NDIM${NDIM}.o				\
	StandardCoarsenTransactionFactory-NDIM${NDIM}.o			\
	StandardLocallyActiveDataCoarsenTransactionFactory-NDIM${NDIM}.o\
	StandardLocallyActiveDataRefineTransactionFactory-NDIM${NDIM}.o	\
	StandardRefineTransactionFactory-NDIM${NDIM}.o			\
	TimeInterpolateOperator-NDIM${NDIM}.o				\
	VariableFillPattern-NDIM${NDIM}.o				\
	tbox__List-xfer__CoarsenClasses_NDIM___Data${NDIM}.o		\
	tbox__List-xfer__MultiblockRefineSchedule_NDIM___SingularityPatch${NDIM}.o\
	tbox__List-xfer__RefineClasses_NDIM___Data${NDIM}.o		\
	tbox__Array-tbox__List-xfer__CoarsenClasses_NDIM___Data${NDIM}.o\
	tbox__Array-tbox__List-xfer__MultiblockRefineSchedule_NDIM___SingularityPatch${NDIM}.o\
	tbox__Array-tbox__List-xfer__RefineClasses_NDIM___Data${NDIM}.o	\
	tbox__Array-xfer__FillBoxSet-NDIM${NDIM}.o			\
	tbox__Array-xfer__LocallyActiveDataFillBoxSet-NDIM${NDIM}.o	\
	tbox__List-xfer__LocallyActiveDataFillBox-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__BoxGeometryFillPattern-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__CoarsenAlgorithm-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__CoarsenClasses-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__CoarsenOperator-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__CoarsenSchedule-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__CoarsenTransactionFactory-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__Geometry-NDIM${NDIM}.o			\
	tbox__Pointer-xfer__LocallyActiveDataCoarsenAlgorithm-NDIM${NDIM}.o\
	tbox__Pointer-xfer__LocallyActiveDataCoarsenSchedule-NDIM${NDIM}.o\
	tbox__Pointer-xfer__LocallyActiveDataCoarsenTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__LocallyActiveDataRefineAlgorithm-NDIM${NDIM}.o\
	tbox__Pointer-xfer__LocallyActiveDataRefineSchedule-NDIM${NDIM}.o\
	tbox__Pointer-xfer__LocallyActiveDataRefineTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__MultiblockCoarsenAlgorithm-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__MultiblockCoarsenSchedule-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__MultiblockRefineAlgorithm-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__MultiblockRefineSchedule-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__RefineAlgorithm-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__RefineClasses-NDIM${NDIM}.o			\
	tbox__Pointer-xfer__RefineOperator-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__RefineSchedule-NDIM${NDIM}.o		\
	tbox__Pointer-xfer__RefineTransactionFactory-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__StandardCoarsenTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__StandardLocallyActiveDataCoarsenTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__StandardLocallyActiveDataRefineTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__StandardRefineTransactionFactory-NDIM${NDIM}.o\
	tbox__Pointer-xfer__TimeInterpolateOperator-NDIM${NDIM}.o	\
	tbox__Pointer-xfer__VariableFillPattern-NDIM${NDIM}.o		\
	tbox__Array-tbox__Array-xfer__FillBoxSet-NDIM${NDIM}.o		\
	tbox__Array-tbox__Pointer-xfer__CoarsenSchedule-NDIM${NDIM}.o	\
	tbox__Array-tbox__Pointer-xfer__LocallyActiveDataCoarsenSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-xfer__LocallyActiveDataRefineSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-xfer__MultiblockRefineSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Pointer-xfer__RefineSchedule-NDIM${NDIM}.o	\
	tbox__List-tbox__Pointer-xfer__CoarsenOperator-NDIM${NDIM}.o	\
	tbox__List-tbox__Pointer-xfer__LocallyActiveDataRefineSchedule-NDIM${NDIM}.o\
	tbox__List-tbox__Pointer-xfer__RefineOperator-NDIM${NDIM}.o	\
	tbox__List-tbox__Pointer-xfer__RefineSchedule-NDIM${NDIM}.o	\
	tbox__List-tbox__Pointer-xfer__TimeInterpolateOperator-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Pointer-xfer__LocallyActiveDataRefineSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Pointer-xfer__MultiblockRefineSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Pointer-xfer__RefineSchedule-NDIM${NDIM}.o\
	tbox__Array-tbox__Array-tbox__Array-tbox__Pointer-xfer__RefineSchedule-NDIM${NDIM}.o


libchar:	


libbool:	


libfloat:	


libdcomplex:	
