//
// File:	MultiblockCoarsenAlgorithm-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "MultiblockCoarsenAlgorithm.h"
#include "MultiblockCoarsenAlgorithm.C"

namespace SAMRAI {
   namespace xfer {
template class MultiblockCoarsenAlgorithm< NDIM >;
}
}
