//
// File:	RefineSchedule-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "RefineSchedule.h"
#include "RefineSchedule.C"

namespace SAMRAI {
   namespace xfer {
template class RefineSchedule< NDIM >;
}
}
