//
// File:	RefineAlgorithm-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "RefineAlgorithm.h"
#include "RefineAlgorithm.C"

namespace SAMRAI {
   namespace xfer {
template class RefineAlgorithm< NDIM >;
}
}
