//
// File:	StandardRefineTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "StandardRefineTransactionFactory.h"
#include "StandardRefineTransactionFactory.C"

namespace SAMRAI {
   namespace xfer {
template class StandardRefineTransactionFactory< NDIM >;
}
}
