//
// File:	StandardCoarsenTransactionFactory-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "StandardCoarsenTransactionFactory.h"
#include "StandardCoarsenTransactionFactory.C"

namespace SAMRAI {
   namespace xfer {
template class StandardCoarsenTransactionFactory< NDIM >;
}
}
