//
// File:	tbox__List-xfer__MultiblockRefineSchedule_NDIM___SingularityPatchX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "MultiblockRefineSchedule.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch > *tbox::ListNode< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch >::s_free_list=0;
bool tbox::ListNode< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch >::s_registered_callback=false;
#endif
template class tbox::List< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch >;
template class tbox::ListIterator< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch >;
template class tbox::ListNode< xfer::MultiblockRefineSchedule<NDIM>::SingularityPatch >;
}
}
