//
// File:	tbox__List-xfer__RefineClasses_NDIM___DataX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "tbox/List.h"
#include "tbox/List.C"
#include "RefineClasses.h"

namespace SAMRAI {
   namespace tbox {
#ifdef LACKS_STATIC_DATA_INSTANTIATION
tbox::ListNode< xfer::RefineClasses<NDIM>::Data > *tbox::ListNode< xfer::RefineClasses<NDIM>::Data >::s_free_list=0;
bool tbox::ListNode< xfer::RefineClasses<NDIM>::Data >::s_registered_callback=false;
#endif
template class tbox::List< xfer::RefineClasses<NDIM>::Data >;
template class tbox::ListIterator< xfer::RefineClasses<NDIM>::Data >;
template class tbox::ListNode< xfer::RefineClasses<NDIM>::Data >;
}
}
