//
// File:	VariableFillPattern-NDIMX.C
// Package:	SAMRAI templates
// Copyright:	(c) 1997-2008 Lawrence Livermore National Security, LLC
// Description:	Template file automatically generated by make-template.pl
//

#include "VariableFillPattern.h"
#include "VariableFillPattern.C"

namespace SAMRAI {
   namespace xfer {
template class VariableFillPattern< NDIM >;
}
}
